import json
import os

NOTEBOOK_PATH = r"d:\mduy\source\repos\EXACT\src\llm\tuning\train_folc_kaggle.ipynb"

print(f"Loading {NOTEBOOK_PATH}...")
with open(NOTEBOOK_PATH, "r", encoding="utf-8") as f:
    nb = json.load(f)

# Find Cell 6 (id "0ece368f")
target_cell = None
for cell in nb["cells"]:
    if cell["cell_type"] == "code" and cell.get("id") == "0ece368f":
        target_cell = cell
        break

if not target_cell:
    raise ValueError("Could not find code cell with ID '0ece368f'")

print("Patching cell '0ece368f' source...")

new_source = [
    "# 6. Configure SFTTrainer and start training\n",
    "import os\n",
    "import glob\n",
    "import torch\n",
    "import json\n",
    "import random\n",
    "from trl import SFTTrainer, SFTConfig\n",
    "from transformers import TrainerCallback, DataCollatorForLanguageModeling\n",
    "from typing import Dict, Union, Any, Optional, List, Tuple\n",
    "\n",
    "class LossLoggingCallback(TrainerCallback):\n",
    "    def on_log(self, args, state, control, logs=None, **kwargs):\n",
    "        if logs is not None:\n",
    "            if \"loss\" in logs:\n",
    "                print(f\"Step {state.global_step}: training_loss = {logs['loss']:.6f}\")\n",
    "            if \"eval_loss\" in logs:\n",
    "                print(f\"Step {state.global_step}: validation_loss = {logs['eval_loss']:.6f}\")\n",
    "\n",
    "class CustomDataCollator(DataCollatorForLanguageModeling):\n",
    "    def __init__(self, response_template, tokenizer, *args, **kwargs):\n",
    "        super().__init__(tokenizer=tokenizer, mlm=False, *args, **kwargs)\n",
    "        self.response_template = response_template\n",
    "        self.response_token_ids = self.tokenizer.encode(self.response_template, add_special_tokens=False)\n",
    "        \n",
    "    def __call__(self, examples):\n",
    "        batch = super().__call__(examples)\n",
    "        labels = batch[\"labels\"]\n",
    "        for i in range(labels.size(0)):\n",
    "            input_ids = batch[\"input_ids\"][i].tolist()\n",
    "            response_idx = -1\n",
    "            n_template = len(self.response_token_ids)\n",
    "            for j in range(len(input_ids) - n_template + 1):\n",
    "                if input_ids[j:j+n_template] == self.response_token_ids:\n",
    "                    response_idx = j + n_template\n",
    "                    break\n",
    "            \n",
    "            if response_idx != -1:\n",
    "                labels[i, :response_idx] = -100\n",
    "                \n",
    "        return batch\n",
    "\n",
    "# --- OFFLINE FOL PARSER (HARDCODED FROM src/logic/reasoning/parser.py) ---\n",
    "try:\n",
    "    import z3\n",
    "    from z3 import (\n",
    "        And,\n",
    "        BoolSort,\n",
    "        Const,\n",
    "        DeclareSort,\n",
    "        Exists,\n",
    "        ForAll,\n",
    "        Function,\n",
    "        IntSort,\n",
    "        IntVal,\n",
    "        Not,\n",
    "        Or,\n",
    "        RealSort,\n",
    "        RealVal,\n",
    "        StringVal,\n",
    "        BoolRef,\n",
    "        ExprRef,\n",
    "    )\n",
    "    import re\n",
    "    import threading\n",
    "    from typing import Dict, Iterable, List, Optional, Tuple\n",
    "    \n",
    "    _TOKEN_RE = re.compile(\n",
    "        r\"\\s*(->|<->|AND|OR|NOT|IN|ForAll|Exists|>=|<=|!=|=|>|<|\\(|\\)|,|\\+|-|\\d+\\.\\d+|\\d+|'[^']*'|[^\\W\\d][\\w-]*)\"\n",
    "    )\n",
    "    \n",
    "    class Z3Symbols:\n",
    "        def __init__(self, sort: ExprRef) -> None:\n",
    "            self.sort = sort\n",
    "            self.consts: Dict[str, ExprRef] = {}\n",
    "            self.preds: Dict[Tuple[str, int], ExprRef] = {}\n",
    "            self.funcs: Dict[Tuple[str, int], ExprRef] = {}\n",
    "            self.numeric_symbols: set[str] = set()\n",
    "    \n",
    "        def get_const(self, name: str, sort: Optional[ExprRef] = None) -> ExprRef:\n",
    "            if name in self.consts:\n",
    "                return self.consts[name]\n",
    "            use_sort = sort\n",
    "            if use_sort is None:\n",
    "                use_sort = RealSort() if name in self.numeric_symbols else self.sort\n",
    "            const = Const(name, use_sort)\n",
    "            self.consts[name] = const\n",
    "            return const\n",
    "    \n",
    "        def get_pred(self, name: str, arity: int) -> ExprRef:\n",
    "            key = (name, arity)\n",
    "            if key in self.preds:\n",
    "                return self.preds[key]\n",
    "            if name in self.numeric_symbols:\n",
    "                return self.get_func(name, arity, RealSort())\n",
    "            pred = Function(name, *([self.sort] * arity), BoolSort())\n",
    "            self.preds[key] = pred\n",
    "            return pred\n",
    "    \n",
    "        def get_func(self, name: str, arity: int, sort: Optional[ExprRef] = None) -> ExprRef:\n",
    "            key = (name, arity)\n",
    "            if key in self.funcs:\n",
    "                return self.funcs[key]\n",
    "            use_sort = sort\n",
    "            if use_sort is None:\n",
    "                use_sort = RealSort() if name in self.numeric_symbols else self.sort\n",
    "            func = Function(name, *([self.sort] * arity), use_sort)\n",
    "            self.funcs[key] = func\n",
    "            return func\n",
    "            \n",
    "    class TokenStream:\n",
    "        def __init__(self, text: str) -> None:\n",
    "            self.tokens = [t for t in _TOKEN_RE.findall(text) if t.strip()]\n",
    "            self.index = 0\n",
    "    \n",
    "        def peek(self) -> Optional[str]:\n",
    "            if self.index >= len(self.tokens):\n",
    "                return None\n",
    "            return self.tokens[self.index]\n",
    "    \n",
    "        def peek_offset(self, offset: int) -> Optional[str]:\n",
    "            idx = self.index + offset\n",
    "            if idx >= len(self.tokens):\n",
    "                return None\n",
    "            return self.tokens[idx]\n",
    "    \n",
    "        def next(self) -> Optional[str]:\n",
    "            tok = self.peek()\n",
    "            if tok is not None:\n",
    "                self.index += 1\n",
    "            return tok\n",
    "    \n",
    "        def expect(self, value: str) -> None:\n",
    "            tok = self.next()\n",
    "            if tok != value:\n",
    "                raise ValueError(f\"Expected '{value}', got '{tok}'\")\n",
    "                \n",
    "    class FolParser:\n",
    "        def __init__(self, symbols: Z3Symbols) -> None:\n",
    "            self.symbols = symbols\n",
    "            self.var_stack: List[Dict[str, ExprRef]] = []\n",
    "    \n",
    "        def parse(self, text: str) -> BoolRef:\n",
    "            stream = TokenStream(text)\n",
    "            expr = self._parse_implication(stream)\n",
    "            return expr\n",
    "    \n",
    "        def _parse_implication(self, stream: TokenStream) -> BoolRef:\n",
    "            left = self._parse_or(stream)\n",
    "            tok = stream.peek()\n",
    "            if tok == \"->\":\n",
    "                stream.next()\n",
    "                right = self._parse_implication(stream)\n",
    "                return Or(Not(left), right)\n",
    "            if tok == \"<->\":\n",
    "                stream.next()\n",
    "                right = self._parse_implication(stream)\n",
    "                return And(Or(Not(left), right), Or(Not(right), left))\n",
    "            return left\n",
    "    \n",
    "        def _parse_or(self, stream: TokenStream) -> BoolRef:\n",
    "            left = self._parse_and(stream)\n",
    "            while stream.peek() == \"OR\":\n",
    "                stream.next()\n",
    "                right = self._parse_and(stream)\n",
    "                left = Or(left, right)\n",
    "            return left\n",
    "    \n",
    "        def _parse_and(self, stream: TokenStream) -> BoolRef:\n",
    "            left = self._parse_not(stream)\n",
    "            while stream.peek() == \"AND\":\n",
    "                stream.next()\n",
    "                right = self._parse_not(stream)\n",
    "                left = And(left, right)\n",
    "            return left\n",
    "    \n",
    "        def _parse_not(self, stream: TokenStream) -> BoolRef:\n",
    "            if stream.peek() == \"NOT\":\n",
    "                stream.next()\n",
    "                return Not(self._parse_not(stream))\n",
    "            return self._parse_atom(stream)\n",
    "    \n",
    "        def _parse_atom(self, stream: TokenStream) -> BoolRef:\n",
    "            tok = stream.peek()\n",
    "            if tok is None:\n",
    "                raise ValueError(\"Unexpected end of input\")\n",
    "            if tok == \"(\":\n",
    "                stream.next()\n",
    "                expr = self._parse_implication(stream)\n",
    "                stream.expect(\")\")\n",
    "                return expr\n",
    "            if tok in (\"ForAll\", \"Exists\"):\n",
    "                return self._parse_quantifier(stream)\n",
    "            start_index = stream.index\n",
    "            term = self._parse_term(stream)\n",
    "            comp = stream.peek()\n",
    "            if comp == \"IN\":\n",
    "                stream.next()\n",
    "                right = self._parse_term(stream)\n",
    "                pred = self.symbols.get_pred(\"In\", 2)\n",
    "                return pred(term, right)\n",
    "            if comp in (\"=\", \"!=\", \">=\", \"<=\", \">\", \"<\"):\n",
    "                numeric = comp in (\">=\", \"<=\", \">\", \"<\")\n",
    "                if comp in (\"=\", \"!=\"):\n",
    "                    next_tok = stream.peek_offset(1)\n",
    "                    if next_tok is not None and re.fullmatch(r\"\\d+(?:\\.\\d+)?\", next_tok):\n",
    "                        numeric = True\n",
    "                if numeric and isinstance(term, BoolRef):\n",
    "                    stream.index = start_index\n",
    "                    term = self._parse_term(stream, prefer_numeric=True)\n",
    "                    comp = stream.peek()\n",
    "                stream.next()\n",
    "                right = self._parse_term(stream, prefer_numeric=numeric)\n",
    "                return self._build_comparison(comp, term, right)\n",
    "            if not isinstance(term, BoolRef):\n",
    "                raise ValueError(\"Predicate expected, got term\")\n",
    "            return term\n",
    "    \n",
    "        def _parse_quantifier(self, stream: TokenStream) -> BoolRef:\n",
    "            quant = stream.next()\n",
    "            stream.expect(\"(\")\n",
    "            var_name = stream.next()\n",
    "            if var_name is None:\n",
    "                raise ValueError(\"Missing quantified variable\")\n",
    "            stream.expect(\",\")\n",
    "            var = Const(var_name, self.symbols.sort)\n",
    "            self.var_stack.append({var_name: var})\n",
    "            body = self._parse_implication(stream)\n",
    "            self.var_stack.pop()\n",
    "            stream.expect(\")\")\n",
    "            if quant == \"ForAll\":\n",
    "                return ForAll([var], body)\n",
    "            return Exists([var], body)\n",
    "    \n",
    "        def _parse_term(self, stream: TokenStream, prefer_numeric: bool = False) -> ExprRef:\n",
    "            left = self._parse_simple_term(stream, prefer_numeric=prefer_numeric)\n",
    "            while stream.peek() in (\"+\", \"-\"):\n",
    "                op = stream.next()\n",
    "                right = self._parse_simple_term(stream, prefer_numeric=True)\n",
    "                if op == \"+\":\n",
    "                    left = left + right\n",
    "                else:\n",
    "                    left = left - right\n",
    "            return left\n",
    "    \n",
    "        def _parse_simple_term(self, stream: TokenStream, prefer_numeric: bool = False) -> ExprRef:\n",
    "            tok = stream.next()\n",
    "            if tok is None:\n",
    "                raise ValueError(\"Unexpected end of input\")\n",
    "            if tok == \"(\":\n",
    "                expr = self._parse_term(stream, prefer_numeric=prefer_numeric)\n",
                "                stream.expect(\")\")\n",
                "                return expr\n",
            "            if tok.startswith(\"'\") and tok.endswith(\"'\"):\n",
            "                return StringVal(tok[1:-1])\n",
    "    \n",
            "            time_match = re.match(r\"^Time(\\d{1,2})(\\d{2})?(AM|PM)$\", tok, re.IGNORECASE)\n",
            "            if time_match:\n",
            "                hour = int(time_match.group(1))\n",
            "                minute = int(time_match.group(2)) if time_match.group(2) else 0\n",
            "                ampm = time_match.group(3).upper()\n",
            "                if ampm == \"PM\" and hour < 12:\n",
            "                    hour += 12\n",
            "                elif ampm == \"AM\" and hour == 12:\n",
            "                    hour = 0\n",
            "                minutes = hour * 60 + minute\n",
            "                return IntVal(minutes)\n",
    "    \n",
            "            duration_match = re.match(r\"^Duration(\\d+(?:\\.\\d+)?)(Hours|Minutes|Days)$\", tok, re.IGNORECASE)\n",
            "            if duration_match:\n",
            "                value = float(duration_match.group(1))\n",
            "                unit = duration_match.group(2).lower()\n",
            "                if unit == \"hours\":\n",
            "                    minutes = int(value * 60)\n",
            "                elif unit == \"days\":\n",
            "                    minutes = int(value * 24 * 60)\n",
            "                else:\n",
            "                    minutes = int(value)\n",
            "                return IntVal(minutes)\n",
    "    \n",
            "            if tok.replace(\".\", \"\", 1).isdigit():\n",
            "                if \".\" in tok:\n",
            "                    return RealVal(tok)\n",
            "                return IntVal(tok)\n",
            "            var = self._lookup_var(tok)\n",
            "            if var is not None:\n",
            "                return var\n",
            "            if stream.peek() == \"(\":\n",
            "                stream.next()\n",
            "                args = []\n",
            "                if stream.peek() != \")\":\n",
            "                    while True:\n",
            "                        args.append(self._parse_term(stream, prefer_numeric=prefer_numeric))\n",
            "                        if stream.peek() == \",\":\n",
            "                            stream.next()\n",
            "                            continue\n",
            "                        break\n",
            "                stream.expect(\")\")\n",
            "                if prefer_numeric:\n",
            "                    func = self.symbols.get_func(tok, len(args), RealSort())\n",
            "                    return func(*args)\n",
            "                pred = self.symbols.get_pred(tok, len(args))\n",
            "                return pred(*args)\n",
            "            if prefer_numeric:\n",
            "                return self.symbols.get_const(tok, RealSort())\n",
            "            return self.symbols.get_const(tok)\n",
    "    \n",
    "        def _build_comparison(self, op: str, left: ExprRef, right: ExprRef) -> BoolRef:\n",
    "            if op == \"=\":\n",
    "                return left == right\n",
    "            if op == \"!=\":\n",
    "                return left != right\n",
    "            if op == \">=\":\n",
    "                return left >= right\n",
    "            if op == \"<=\":\n",
    "                return left <= right\n",
    "            if op == \">\".encode('ascii').decode('ascii'):  # Avoid json parser escape issues\n",
    "                return left > right\n",
    "            if op == \"<\":\n",
    "                return left < right\n",
    "            raise ValueError(f\"Unsupported comparator: {op}\")\n",
    "    \n",
    "        def _lookup_var(self, name: str) -> Optional[ExprRef]:\n",
    "            for scope in reversed(self.var_stack):\n",
    "                if name in scope:\n",
    "                    return scope[name]\n",
    "            return None\n",
    "\n",
    "    def parse_formulas(formulas, sort_name=\"U\"):\n",
    "        numeric_symbols = set()\n",
    "        for f in formulas:\n",
    "            f_temp = f.replace(\"<->\", \" BICOND \").replace(\"->\", \" IMPLIES \")\n",
    "            \n",
    "            left_matches = re.finditer(r\"\\b([A-Za-z_][A-Za-z0-9_-]*)\\s*(?:\\([^()]*\\))?\\s*(?:>=|<=|>|<|\\+|-)\\b\", f_temp)\n",
    "            for m in left_matches:\n",
    "                name = m.group(1)\n",
    "                if name not in (\"ForAll\", \"Exists\", \"AND\", \"OR\", \"NOT\", \"IN\", \"BICOND\", \"IMPLIES\"):\n",
    "                    numeric_symbols.add(name)\n",
    "                    \n",
    "            right_matches = re.finditer(r\"\\b(?:>=|<=|>|<|\\+|-)\\s*([A-Za-z_][A-Za-z0-9_-]*)\\b\", f_temp)\n",
    "            for m in right_matches:\n",
    "                name = m.group(1)\n",
    "                if name not in (\"ForAll\", \"Exists\", \"AND\", \"OR\", \"NOT\", \"IN\", \"BICOND\", \"IMPLIES\"):\n",
    "                    numeric_symbols.add(name)\n",
    "                    \n",
    "            eq_matches = re.finditer(r\"\\b([A-Za-z_][A-Za-z0-9_-]*)\\s*(?:\\([^()]*\\))?\\s*(?:=|!=)\\s*(?:\\d+(?:\\.\\d+)?|Time\\d+[A-Za-z]+|Duration\\d+[A-Z]+)\\b\", f_temp)\n",
    "            for m in eq_matches:\n",
    "                name = m.group(1)\n",
    "                if name not in (\"ForAll\", \"Exists\", \"AND\", \"OR\", \"NOT\", \"IN\", \"BICOND\", \"IMPLIES\"):\n",
    "                    numeric_symbols.add(name)\n",
    "                    \n",
    "            eq_rev_matches = re.finditer(r\"\\b(?:\\d+(?:\\.\\d+)?|Time\\d+[A-Za-z]+|Duration\\d+[A-Z]+)\\s*(?:=|!=)\\s*([A-Za-z_][A-Za-z0-9_-]*)\\b\", f_temp)\n",
    "            for m in eq_rev_matches:\n",
    "                name = m.group(1)\n",
    "                if name not in (\"ForAll\", \"Exists\", \"AND\", \"OR\", \"NOT\", \"IN\", \"BICOND\", \"IMPLIES\"):\n",
    "                    numeric_symbols.add(name)\n",
    "    \n",
    "        symbols = Z3Symbols(sort=DeclareSort(sort_name))\n",
    "        symbols.numeric_symbols = numeric_symbols\n",
    "        \n",
    "        parser = FolParser(symbols)\n",
    "        formula_exprs = [parser.parse(f) for f in formulas]\n",
    "        return symbols, formula_exprs\n",
    "\n",
    "    _z3_lock = threading.Lock()\n",
    "    \n",
    "    def try_parse_fol(formula: str) -> tuple[bool, str]:\n",
    "        with _z3_lock:\n",
    "            try:\n",
    "                parse_formulas([formula])\n",
    "                return True, \"\"\n",
    "            except Exception as exc:\n",
    "                return False, str(exc)\n",
    "                \n",
    "    fol_parser_available = True\n",
    "    print(\"Offline Z3 logic parser successfully initialized.\")\n",
    "except ImportError:\n",
    "    fol_parser_available = False\n",
    "    print(\"Warning: Z3 or logic parser not available. Using basic syntax checking (parentheses/operators).\")\n",
    "    \n",
    "    def try_parse_fol(formula: str) -> tuple[bool, str]:\n",
    "        return False, \"Z3 solver library not installed.\"\n",
    "\n",
    "# --- ACCURACY EVALUATION HELPERS ---\n",
    "def compare_physics_answers(pred_ans, pred_unit, gt_ans, gt_unit):\n",
    "    if pred_ans is None or gt_ans is None:\n",
    "        return False\n",
    "    if not isinstance(pred_ans, list):\n",
    "        pred_ans = [pred_ans]\n",
    "    if not isinstance(gt_ans, list):\n",
    "        gt_ans = [gt_ans]\n",
    "    if len(pred_ans) != len(gt_ans):\n",
    "        return False\n",
    "    for p_val, g_val in zip(pred_ans, gt_ans):\n",
    "        try:\n",
    "            p_num = float(p_val)\n",
    "            g_num = float(g_val)\n",
    "            if g_num == 0.0:\n",
    "                if abs(p_num) >= 1e-5:\n",
    "                    return False\n",
    "            else:\n",
    "                rel_err = abs(p_num - g_num) / abs(g_num)\n",
    "                if rel_err > 0.02:  # 2% tolerance\n",
    "                    return False\n",
    "        except (ValueError, TypeError):\n",
    "            if str(p_val).strip().lower() != str(g_val).strip().lower():\n",
    "                return False\n",
    "    return True\n",
    "\n",
    "def basic_validate_fol(formula: str) -> bool:\n",
    "    if formula.count(\"(\") != formula.count(\")\"):\n",
    "        return False\n",
    "    for bad in [\" and \", \" or \", \" not \"]:\n",
    "        if bad in formula:\n",
    "            return False\n",
    "    for bad_q in [\"forall(\", \"exists(\"]:\n",
    "        if bad_q in formula.lower() and not (bad_q.capitalize() in formula or \"ForAll\" in formula or \"Exists\" in formula):\n",
    "            return False\n",
    "    return True\n",
    "\n",
    "def evaluate_fol_accuracy(model, tokenizer, val_samples, limit=50):\n",
    "    print(f\"Evaluating FOL Accuracy on {min(len(val_samples), limit)} samples...\")\n",
    "    correct_count = 0\n",
    "    total_count = 0\n",
    "    valid_json_count = 0\n",
    "    syntax_valid_count = 0\n",
    "    formula_correct = 0\n",
    "    formula_total = 0\n",
    "    \n",
    "    # Shuffle and sample to keep evaluation fast\n",
    "    random_subset = random.Random(42).sample(val_samples, min(len(val_samples), limit))\n",
    "    \n",
    "    for item in random_subset:\n",
    "        nl_list = item[\"premises-NL\"]\n",
    "        fol_list_gt = item[\"premises-FOL\"]\n",
    "        \n",
    "        nl_content = \"\"\n",
    "        for i, nl in enumerate(nl_list, start=1):\n",
    "            nl_content += f\"{i}. {nl}\\n\"\n",
    "            \n",
    "        user_prompt = user_prompt_template.format(num_premises=len(nl_list), premises=nl_content.strip())\n",
    "        messages = [\n",
    "            {\"role\": \"system\", \"content\": system_prompt_template},\n",
    "            {\"role\": \"user\", \"content\": user_prompt.strip()}\n",
    "        ]\n",
    "        \n",
    "        prompt_text = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)\n",
    "        inputs = tokenizer(prompt_text, return_tensors=\"pt\").to(model.device)\n",
    "        \n",
    "        with torch.no_grad():\n",
    "            outputs = model.generate(\n",
    "                **inputs,\n",
    "                max_new_tokens=512,\n",
    "                do_sample=False,\n",
    "                pad_token_id=tokenizer.pad_token_id,\n",
    "                eos_token_id=tokenizer.eos_token_id\n",
    "            )\n",
    "            \n",
    "        generated_ids = outputs[0][inputs.input_ids.shape[1]:]\n",
    "        response = tokenizer.decode(generated_ids, skip_special_tokens=True).strip()\n",
    "        \n",
    "        try:\n",
    "            parsed_response = json.loads(response)\n",
    "            valid_json_count += 1\n",
    "            if isinstance(parsed_response, list):\n",
    "                all_formulas_valid = True\n",
    "                for formula in parsed_response:\n",
    "                    if fol_parser_available:\n",
    "                        try:\n",
    "                            is_valid, _ = try_parse_fol(str(formula))\n",
    "                            if not is_valid:\n",
    "                                all_formulas_valid = False\n",
    "                                break\n",
    "                        except Exception:\n",
    "                            if not basic_validate_fol(str(formula)):\n",
    "                                all_formulas_valid = False\n",
    "                                break\n",
    "                    else:\n",
    "                        if not basic_validate_fol(str(formula)):\n",
    "                            all_formulas_valid = False\n",
    "                            break\n",
    "                if all_formulas_valid:\n",
    "                    syntax_valid_count += 1\n",
    "                \n",
    "                if isinstance(fol_list_gt, list):\n",
    "                    if [str(x).strip() for x in parsed_response] == [str(x).strip() for x in fol_list_gt]:\n",
    "                        correct_count += 1\n",
    "                    \n",
    "                    matched_formulas = 0\n",
    "                    for p_f, g_f in zip(parsed_response, fol_list_gt):\n",
    "                        if str(p_f).strip() == str(g_f).strip():\n",
    "                            matched_formulas += 1\n",
    "                    formula_correct += matched_formulas\n",
    "                    formula_total += len(fol_list_gt)\n",
    "        except Exception:\n",
    "            pass\n",
    "        total_count += 1\n",
    "        \n",
    "    em_acc = (correct_count / total_count) * 100 if total_count > 0 else 0\n",
    "    formula_acc = (formula_correct / formula_total) * 100 if formula_total > 0 else 0\n",
    "    json_rate = (valid_json_count / total_count) * 100 if total_count > 0 else 0\n",
    "    syntax_rate = (syntax_valid_count / total_count) * 100 if total_count > 0 else 0\n",
    "    \n",
    "    print(\"\\n=== FOL Evaluation Metrics ===\")\n",
    "    print(f\"FOL Exact Match Accuracy (Sample Level): {em_acc:.2f}% ({correct_count}/{total_count})\")\n",
    "    print(f\"FOL Formula Level Match Accuracy: {formula_acc:.2f}% ({formula_correct}/{formula_total})\")\n",
    "    print(f\"FOL Syntax Validity Rate: {syntax_rate:.2f}% ({syntax_valid_count}/{total_count})\")\n",
    "    print(f\"FOL JSON Validity Rate: {json_rate:.2f}% ({valid_json_count}/{total_count})\")\n",
    "    return em_acc, json_rate, syntax_rate\n",
    "\n",
    "def evaluate_physics_accuracy(model, tokenizer, val_samples, limit=50):\n",
    "    print(f\"Evaluating Physics Accuracy on {min(len(val_samples), limit)} samples...\")\n",
    "    correct_count = 0\n",
    "    total_count = 0\n",
    "    valid_json_count = 0\n",
    "    python_syntax_count = 0\n",
    "    exec_count = 0\n",
    "    \n",
    "    random_subset = random.Random(42).sample(val_samples, min(len(val_samples), limit))\n",
    "    \n",
    "    for item in random_subset:\n",
    "        inp = item[\"input\"]\n",
    "        gt_output_str = item[\"output\"]\n",
    "        \n",
    "        messages = [\n",
    "            {\"role\": \"system\", \"content\": physics_system_prompt},\n",
    "            {\"role\": \"user\", \"content\": inp.strip()}\n",
    "        ]\n",
    "        \n",
    "        prompt_text = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)\n",
    "        inputs = tokenizer(prompt_text, return_tensors=\"pt\").to(model.device)\n",
    "        \n",
    "        with torch.no_grad():\n",
    "            outputs = model.generate(\n",
    "                **inputs,\n",
    "                max_new_tokens=512,\n",
    "                do_sample=False,\n",
    "                pad_token_id=tokenizer.pad_token_id,\n",
    "                eos_token_id=tokenizer.eos_token_id\n",
    "            )\n",
    "            \n",
    "        generated_ids = outputs[0][inputs.input_ids.shape[1]:]\n",
    "        response = tokenizer.decode(generated_ids, skip_special_tokens=True).strip()\n",
    "        \n",
    "        try:\n",
    "            parsed_response = json.loads(response)\n",
    "            valid_json_count += 1\n",
    "            code_str = parsed_response.get(\"python_code\", \"\")\n",
    "            \n",
    "            try:\n",
    "                gt_parsed = json.loads(gt_output_str)\n",
    "                gt_code_str = gt_parsed.get(\"python_code\", \"\")\n",
    "            except Exception:\n",
    "                gt_code_str = \"\"\n",
    "                \n",
    "            if code_str:\n",
    "                try:\n",
    "                    compile(code_str, \"<string>\", \"exec\")\n",
    "                    python_syntax_count += 1\n",
    "                except Exception:\n",
    "                    pass\n",
    "\n",
    "                if gt_code_str:\n",
    "                    local_vars_pred = {}\n",
    "                    local_vars_gt = {}\n",
    "                    try:\n",
    "                        import sympy as sp\n",
    "                        exec(code_str, {\"sp\": sp}, local_vars_pred)\n",
    "                        pred_ans = local_vars_pred.get(\"ans\", None)\n",
    "                        pred_unit = local_vars_pred.get(\"unit\", None)\n",
    "                        \n",
    "                        exec(gt_code_str, {\"sp\": sp}, local_vars_gt)\n",
    "                        gt_ans = local_vars_gt.get(\"ans\", None)\n",
    "                        gt_unit = local_vars_gt.get(\"unit\", None)\n",
    "                        \n",
    "                        if pred_ans is not None and gt_ans is not None:\n",
    "                            exec_count += 1\n",
    "                            if compare_physics_answers(pred_ans, pred_unit, gt_ans, gt_unit):\n",
    "                                correct_count += 1\n",
    "                    except Exception:\n",
    "                        pass\n",
    "        except Exception:\n",
    "            pass\n",
    "        total_count += 1\n",
    "        \n",
    "    acc = (correct_count / total_count) * 100 if total_count > 0 else 0\n",
    "    json_rate = (valid_json_count / total_count) * 100 if total_count > 0 else 0\n",
    "    python_syntax_rate = (python_syntax_count / total_count) * 100 if total_count > 0 else 0\n",
    "    exec_rate = (exec_count / total_count) * 100 if total_count > 0 else 0\n",
    "    \n",
    "    print(\"\\n=== Physics Evaluation Metrics ===\")\n",
    "    print(f\"Physics Accuracy: {acc:.2f}% ({correct_count}/{total_count})\")\n",
    "    print(f\"Physics JSON Validity Rate: {json_rate:.2f}% ({valid_json_count}/{total_count})\")\n",
    "    print(f\"Physics Python Syntax Validity Rate: {python_syntax_rate:.2f}% ({python_syntax_count}/{total_count})\")\n",
    "    print(f\"Physics Code Execution Rate: {exec_rate:.2f}% ({exec_count}/{total_count})\")\n",
    "    return acc, json_rate, python_syntax_rate, exec_rate\n",
    "\n",
    "def train_model(train_dataset, val_dataset, output_dir):\n",
    "    clean_memory()\n",
    "    \n",
    "    # Mathematically exact, dynamic warmup steps calculation based on actual dataset size\n",
    "    num_samples = len(train_dataset)\n",
    "    effective_batch_size = BATCH_SIZE * GRADIENT_ACCUMULATION\n",
    "    steps_per_epoch = num_samples // effective_batch_size\n",
    "    if num_samples % effective_batch_size != 0:\n",
    "        steps_per_epoch += 1\n",
    "    total_steps = steps_per_epoch * EPOCHS\n",
    "    \n",
    "    # Target exactly 5% warmup steps of total training steps (HF v5.2 compliant integer steps)\n",
    "    warmup_steps = max(1, int(total_steps * 0.05))\n",
    "    print(f\"Training on {num_samples} samples. Steps per epoch: {steps_per_epoch}. Total steps: {total_steps}. Dynamic warmup steps: {warmup_steps}\")\n",
    "    \n",
    "    base_model = load_base_model()\n",
    "    \n",
    "    # Resume from previous checkpoints if adapter_config.json exists in output_dir\n",
    "    adapter_config_path = os.path.join(output_dir, \"adapter_config.json\")\n",
    "    if os.path.exists(adapter_config_path):\n",
    "        print(f\"Resuming PEFT adapter weights from {output_dir}...\")\n",
    "        model = PeftModel.from_pretrained(base_model, output_dir, is_trainable=True)\n",
    "    else:\n",
    "        print(\"Initializing a new PEFT adapter...\")\n",
    "        model = get_peft_model(base_model, peft_config)\n",
    "        \n",
    "    model.print_trainable_parameters()\n",
    "    \n",
    "    # Highly Optimized SFTConfig with Cosine Decay Scheduler & Warmup\n",
    "    sft_config = SFTConfig(\n",
    "        output_dir=output_dir,\n",
    "        num_train_epochs=EPOCHS,\n",
    "        per_device_train_batch_size=BATCH_SIZE,\n",
    "        gradient_accumulation_steps=GRADIENT_ACCUMULATION,\n",
    "        eval_strategy=\"epoch\",\n",
    "        save_strategy=\"epoch\",\n",
    "        learning_rate=LEARNING_RATE,\n",
    "        lr_scheduler_type=\"cosine\",             # Cosine learning rate decay scheduler\n",
    "        warmup_steps=warmup_steps,              # Compliant, dynamic warm-up steps to stabilize updates\n",
    "        fp16=use_fp16,\n",
    "        bf16=use_bf16,\n",
    "        logging_steps=1,\n",
    "        logging_first_step=True,\n",
    "        optim=\"adamw_torch\",\n",
    "        gradient_checkpointing=GRADIENT_CHECKPOINTING,\n",
    "        gradient_checkpointing_kwargs={\"use_reentrant\": False},\n",
    "        per_device_eval_batch_size=BATCH_SIZE,\n",
    "        report_to=\"none\",\n",
    "        load_best_model_at_end=True,\n",
    "        metric_for_best_model=\"eval_loss\",\n",
    "        greater_is_better=False,\n",
    "        save_total_limit=2,\n",
    "        dataset_text_field=\"text\",\n",
    "        max_length=MAX_LENGTH,\n",
    "        neftune_noise_alpha=None,\n",
    "        dataloader_num_workers=2,\n",
    "        dataloader_pin_memory=True\n",
    "    )\n",
    "\n",
    "    response_template = \"<|im_start|>assistant\\n\"\n",
    "    collator = CustomDataCollator(\n",
    "        response_template=response_template, \n",
    "        tokenizer=tokenizer\n",
    "    )\n",
    "    \n",
    "    trainer = SFTTrainer(\n",
    "        model=model,\n",
    "        train_dataset=train_dataset,\n",
    "        eval_dataset=val_dataset,\n",
    "        processing_class=tokenizer,\n",
    "        args=sft_config,\n",
    "        data_collator=collator,\n",
    "        callbacks=[LossLoggingCallback()]\n",
    "    )\n",
    "\n",
    "    checkpoints = glob.glob(os.path.join(output_dir, \"checkpoint-*\"))\n",
    "    resume_path = None\n",
    "    if checkpoints:\n",
    "        checkpoints.sort(key=lambda x: int(x.split(\"-\")[-1]))\n",
    "        resume_path = checkpoints[-1]\n",
    "        print(f\"Found checkpoints. Resuming training from: {resume_path}\")\n",
    "        \n",
    "    trainer.train(resume_from_checkpoint=resume_path)\n",
    "    \n",
    "    print(f\"Saving best validation adapter weights and tokenizer to {output_dir}...\")\n",
    "    trainer.save_model(output_dir)\n",
    "    tokenizer.save_pretrained(output_dir)\n",
    "    print(\"Training completed successfully!\")\n",
    "    \n",
    "    # --- POST-TRAINING ACCURACY EVALUATION ---\n",
    "    try:\n",
    "        print(\"\\n=== Starting Post-Training Accuracy Evaluation ===\")\n",
    "        model.eval()\n",
    "        evaluate_fol_accuracy(model, tokenizer, val_fol, limit=50)\n",
    "        evaluate_physics_accuracy(model, tokenizer, val_physics, limit=50)\n",
    "    except Exception as e:\n",
    "        print(f\"Error during post-training evaluation: {e}\")\n",
    "    \n",
    "    # Clean up model & trainer from memory\n",
    "    del trainer\n",
    "    del model\n",
    "    del base_model\n",
    "    clean_memory()\n"
]

target_cell["source"] = new_source

with open(NOTEBOOK_PATH, "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)

print("Successfully patched train_folc_kaggle.ipynb with hardcoded offline parser!")
