import json

ipynb_path = r"d:\mduy\source\repos\EXACT\src\llm\tuning\folc.ipynb"

with open(ipynb_path, "r", encoding="utf-8") as f:
    nb = json.load(f)

# Find the cell containing "def prepare_hf_dataset"
target_cell = None
for cell in nb["cells"]:
    if cell["cell_type"] == "code":
        source = "".join(cell["source"])
        if "def prepare_hf_dataset" in source:
            target_cell = cell
            break

if target_cell is None:
    print("Could not find the target cell in notebook.")
    exit(1)

# New source code for the cell
new_source = [
    "# 5. Helper Function to Format Dataset (Chat Template) and split Train/Val\n",
    "import json\n",
    "import re\n",
    "import random\n",
    "from datasets import Dataset\n",
    "\n",
    "# Define prompt templates for flat JSON list output with strict count constraint\n",
    "system_prompt_template = (\n",
    "    \"You convert natural-language premises into parser-safe first-order logic formulas.\\n\\n\"\n",
    "    \"Output a STRICT valid JSON list of strings containing the first-order logic formulas in the exact order of the input premises.\\n\"\n",
    "    \"You must output EXACTLY the same number of formulas as the input premises. Do not skip any premises or merge them.\\n\\n\"\n",
    "    \"ALLOWED OPERATORS:\\n\"\n",
    "    \"AND, OR, NOT, ->, <->, =, !=, >=, <=, >, <, ForAll, Exists\\n\\n\"\n",
    "    \"QUANTIFIER RULES:\\n\"\n",
    "    \"Use nested quantifiers only. E.g., ForAll(x, ForAll(y, P(x,y)))\\n\\n\"\n",
    "    \"Return JSON only.\"\n",
    ")\n",
    "\n",
    "user_prompt_template = (\n",
    "    \"Convert the following {num_premises} premises into canonical first-order logic.\\n\\n\"\n",
    "    \"Premises:\\n\"\n",
    "    \"{premises}\\n\\n\"\n",
    "    \"Return a JSON list of exactly {num_premises} strings containing the formulas, in the exact same order.\"\n",
    ")\n",
    "\n",
    "def normalize_fol(formula):\n",
    "    # Standardize spaces and keep logic keywords\n",
    "    keywords = {\"ForAll\", \"Exists\", \"AND\", \"OR\", \"NOT\", \"In\", \"->\", \"<->\", \"=\", \"!=\", \">=\", \"<=\", \">\", \"<\"}\n",
    "    # Extract all word-like identifiers\n",
    "    words = re.findall(r\"\\b[A-Za-z_][A-Za-z0-9_-]*\\b\", formula)\n",
    "    word_map = {}\n",
    "    counter = 0\n",
    "    normalized = formula\n",
    "    for w in words:\n",
    "        if w in keywords or w.isdigit() or w.startswith(\"VAR_\"):\n",
    "            continue\n",
    "        if w not in word_map:\n",
    "            word_map[w] = f\"VAR_{counter}\"\n",
    "            counter += 1\n",
    "        normalized = re.sub(r\"\\b\" + re.escape(w) + r\"\\b\", word_map[w], normalized)\n",
    "    return normalized\n",
    "\n",
    "def get_structure_key(sample):\n",
    "    fol_list = sample.get(\"premises-FOL\", [])\n",
    "    normalized_list = [normalize_fol(f) for f in fol_list]\n",
    "    return \"||\".join(normalized_list)\n",
    "\n",
    "def format_hf_dataset_only(raw_samples, tokenizer):\n",
    "    if not raw_samples:\n",
    "        return None\n",
    "    \n",
    "    formatted_samples = []\n",
    "    for item in raw_samples:\n",
    "        nl_list = item[\"premises-NL\"]\n",
    "        fol_list = item[\"premises-FOL\"]\n",
    "        \n",
    "        # Format premises as a numbered list\n",
    "        nl_content = \"\"\n",
    "        for i, nl in enumerate(nl_list, start=1):\n",
    "            nl_content += f\"{i}. {nl}\\n\"\n",
    "            \n",
    "        # Render user prompt template with count constraint\n",
    "        user_prompt = user_prompt_template.format(num_premises=len(nl_list), premises=nl_content.strip())\n",
    "        \n",
    "        # Assistant response is a flat JSON list of FOL formulas\n",
    "        assistant_response = json.dumps(fol_list, indent=2)\n",
    "        \n",
    "        formatted_samples.append({\n",
    "            \"messages\": [\n",
    "                {\"role\": \"system\", \"content\": system_prompt_template},\n",
    "                {\"role\": \"user\", \"content\": user_prompt.strip()},\n",
    "                {\"role\": \"assistant\", \"content\": assistant_response.strip()}\n",
    "            ]\n",
    "        })\n",
    "\n",
    "    dataset = Dataset.from_list(formatted_samples)\n",
    "\n",
    "    def apply_template(batch):\n",
    "        texts = []\n",
    "        for messages in batch[\"messages\"]:\n",
    "            text = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=False)\n",
    "            texts.append(text)\n",
    "        return {\"text\": texts}\n",
    "\n",
    "    dataset = dataset.map(apply_template, batched=True, remove_columns=[\"messages\"])\n",
    "    return dataset\n",
    "\n",
    "def prepare_hf_dataset(raw_samples, tokenizer, test_size=0.1, seed=42):\n",
    "    if not raw_samples:\n",
    "        return None, None\n",
    "        \n",
    "    # Check if pre-split is defined in the dataset\n",
    "    has_presplit = all(\"split\" in sample for sample in raw_samples)\n",
    "    if has_presplit:\n",
    "        train_samples = [s for s in raw_samples if s.get(\"split\") == \"train\"]\n",
    "        val_samples = [s for s in raw_samples if s.get(\"split\") == \"val\"]\n",
    "        print(f\"Loaded pre-split dataset - Train: {len(train_samples)}, Val: {len(val_samples)}\")\n",
    "    else:\n",
    "        # Group samples by their structure key to prevent structural leakage\n",
    "        groups = {}\n",
    "        for sample in raw_samples:\n",
    "            key = get_structure_key(sample)\n",
    "            if key not in groups:\n",
    "                groups[key] = []\n",
    "            groups[key].append(sample)\n",
    "            \n",
    "        # Sort keys to be 100% deterministic before shuffling\n",
    "        unique_keys = sorted(list(groups.keys()))\n",
    "        \n",
    "        # Shuffle keys deterministically using a local random generator with a fixed seed\n",
    "        rng = random.Random(seed)\n",
    "        rng.shuffle(unique_keys)\n",
    "        \n",
    "        # Split keys\n",
    "        split_idx = int(len(unique_keys) * (1 - test_size))\n",
    "        train_keys = set(unique_keys[:split_idx])\n",
    "        val_keys = set(unique_keys[split_idx:])\n",
    "        \n",
    "        train_samples = []\n",
    "        val_samples = []\n",
    "        for key in unique_keys:\n",
    "            if key in val_keys:\n",
    "                val_samples.extend(groups[key])\n",
    "            else:\n",
    "                train_samples.extend(groups[key])\n",
    "            \n",
    "    # Format to Hugging Face datasets\n",
    "    train_dataset = format_hf_dataset_only(train_samples, tokenizer)\n",
    "    val_dataset = format_hf_dataset_only(val_samples, tokenizer)\n",
    "    \n",
    "    print(f\"Final HF Dataset size - Train: {len(train_dataset)}, Val: {len(val_dataset)}\")\n",
    "    return train_dataset, val_dataset\n"
]

target_cell["source"] = new_source

with open(ipynb_path, "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)

print("Successfully patched folc.ipynb!")
