import json

ipynb_path = r"d:\mduy\source\repos\EXACT\src\llm\tuning\train_folc_kaggle.ipynb"

with open(ipynb_path, "r", encoding="utf-8") as f:
    nb = json.load(f)

# 1. Find the cell containing "def load_translation_dataset" (Cell 3)
loader_cell = None
for cell in nb["cells"]:
    if cell["cell_type"] == "code":
        source = "".join(cell["source"])
        if "def load_translation_dataset" in source:
            loader_cell = cell
            break

if loader_cell is None:
    print("Could not find the loader cell.")
    exit(1)

# New source code for Cell 3 (loader)
new_loader_source = [
    "# 3. Load NL -> FOL translation datasets, Physics dataset, and Physics Prompt\n",
    "import os\n",
    "import json\n",
    "\n",
    "merged_path = \"/kaggle/input/datasets/mduy2911/folc-train/logic_merged_valid_augmented.json\"\n",
    "physics_path = \"/kaggle/input/datasets/mduy2911/folc-train/physics_distillation.json\"\n",
    "\n",
    "def load_translation_dataset(path):\n",
    "    samples = []\n",
    "    seen_premises = set()\n",
    "    with open(path, \"r\", encoding=\"utf-8\") as f:\n",
    "        data = json.load(f)\n",
    "    for item in data:\n",
    "        nl_list = item.get(\"premises-NL\", [])\n",
    "        fol_list = item.get(\"premises-FOL\", [])\n",
    "        if not nl_list or not fol_list or len(nl_list) != len(fol_list):\n",
    "            continue\n",
    "        nl_serialized = \"\\n\".join(nl_list)\n",
    "        if nl_serialized in seen_premises:\n",
    "            continue\n",
    "        seen_premises.add(nl_serialized)\n",
    "        \n",
    "        sample_dict = {\n",
    "            \"premises-NL\": nl_list, \n",
    "            \"premises-FOL\": fol_list,\n",
    "            \"example_id\": item.get(\"example_id\", \"\"),\n",
    "            \"dataset_source\": item.get(\"dataset_source\", \"\")\n",
    "        }\n",
    "        if \"split\" in item:\n",
    "            sample_dict[\"split\"] = item[\"split\"]\n",
    "        samples.append(sample_dict)\n",
    "        \n",
    "    print(f\"Loaded {len(samples)} unique translation samples from {os.path.basename(path)}\")\n",
    "    return samples\n",
    "\n",
    "def load_physics_dataset(path):\n",
    "    samples = []\n",
    "    with open(path, \"r\", encoding=\"utf-8\") as f:\n",
    "        data = json.load(f)\n",
    "    for item in data:\n",
    "        inp = item.get(\"input\", \"\")\n",
    "        out = item.get(\"output\", \"\")\n",
    "        if inp and out:\n",
    "            samples.append({\"input\": inp, \"output\": out})\n",
    "    print(f\"Loaded {len(samples)} physics samples from {os.path.basename(path)}\")\n",
    "    return samples\n",
    "\n",
    "raw_samples = load_translation_dataset(merged_path)\n",
    "physics_samples = load_physics_dataset(physics_path)\n",
    "\n",
    "physics_system_prompt = \"\"\"You are a precise physics reasoning agent.\n",
    "\n",
    "TASK:\n",
    "Convert a physics problem and any provided reasoning policies into executable SymPy code and a valid JSON response.\n",
    "\n",
    "<REASONING_POLICY_OVERRIDE>\n",
    "\n",
    "A <reasoning_policies> block may be provided.\n",
    "\n",
    "If present:\n",
    "\n",
    "1. Treat it as the primary reasoning guidance.\n",
    "\n",
    "2. Follow its definitions, representations, topology rules,\n",
    "   coordinate conventions, state models, and solution procedures.\n",
    "\n",
    "3. Apply the underlying reasoning pattern rather than copying\n",
    "   example expressions verbatim.\n",
    "\n",
    "4. Override a policy only when required for:\n",
    "   - physical validity\n",
    "   - mathematical validity\n",
    "   - SymPy executability\n",
    "\n",
    "</REASONING_POLICY_OVERRIDE>\n",
    "\n",
    "<OPERATING_CONSTRAINTS>\n",
    "\n",
    "Return ONLY:\n",
    "\n",
    "{\n",
    "  \"thought\": \"...\",\n",
    "  \"physics_analysis\": [...],\n",
    "  \"algebraic_reasoning\": [...],\n",
    "  \"python_code\": \"...\",\n",
    "  \"json_terminated\": true\n",
    "}\n",
    "\n",
    "thought format:\n",
    "\n",
    "<detected structure>. <activated reasoning pattern>. <solution strategy>.\n",
    "\n",
    "thought:\n",
    "- concise\n",
    "- high-level\n",
    "- no calculations\n",
    "- no intermediate values\n",
    "- no final values\n",
    "\n",
    "physics_analysis:\n",
    "- concise policy-grounded physical interpretation\n",
    "- record relevant physical facts, assumptions, states, or constraints\n",
    "- no calculations\n",
    "- no final values\n",
    "\n",
    "algebraic_reasoning:\n",
    "- concise policy-grounded symbolic procedure\n",
    "- describe the intended solve workflow\n",
    "- no calculations\n",
    "- no final values\n",
    "\n",
    "python_code:\n",
    "- begin with \"import sympy as sp\"\n",
    "- use sp.Float(...) for numerical constants\n",
    "- define variables before use\n",
    "- solve symbolically before numeric evaluation\n",
    "- evaluate norms, distances, and square roots using float(...) or .evalf()\n",
    "- single-line string only\n",
    "- separate statements using \"; \"\n",
    "- no loops\n",
    "- no functions\n",
    "- no conditional branches\n",
    "- no newline characters\n",
    "\n",
    "Final code statements must define:\n",
    "\n",
    "ans = [...]\n",
    "unit = [...]\n",
    "\n",
    "Requirements:\n",
    "- ans must be a list\n",
    "- unit must be a list\n",
    "- len(ans) == len(unit)\n",
    "- use raw SymPy-computed values\n",
    "- do not manually round or format values\n",
    "- no trailing semicolon after the final statement\n",
    "\n",
    "Use SI base or SI derived units only.\n",
    "Do not use engineering-prefix units.\n",
    "\n",
    "Return the JSON object only.\n",
    "\n",
    "</OPERATING_CONSTRAINTS>\"\"\"\n"
]

loader_cell["source"] = new_loader_source

# 2. Find the cell containing "# 5. Format Dataset (Chat Template)" (Cell 5)
format_cell = None
for cell in nb["cells"]:
    if cell["cell_type"] == "code":
        source = "".join(cell["source"])
        if "# 5. Format Dataset (Chat Template)" in source:
            format_cell = cell
            break

if format_cell is None:
    print("Could not find the formatting cell.")
    exit(1)

# New source code for Cell 5 (splitting and formatting)
new_format_source = [
    "# 5. Format Dataset (Chat Template) and split Train/Val\n",
    "import os\n",
    "import json\n",
    "import random\n",
    "from datasets import Dataset\n",
    "\n",
    "# Define prompt templates for flat JSON list output with strict count constraint\n",
    "system_prompt_template = (\n",
    "    \"You convert natural-language premises into parser-safe first-order logic formulas.\\n\\n\"\n",
    "    \"Output a STRICT valid JSON list of strings containing the first-order logic formulas in the exact order of the input premises.\\n\"\n",
    "    \"You must output EXACTLY the same number of formulas as the input premises. Do not skip any premises or merge them.\\n\\n\"\n",
    "    \"ALLOWED OPERATORS:\\n\"\n",
    "    \"AND, OR, NOT, ->, <->, =, !=, >=, <=, >, <, ForAll, Exists\\n\\n\"\n",
    "    \"QUANTIFIER RULES:\\n\"\n",
    "    \"Use nested quantifiers only. E.g., ForAll(x, ForAll(y, P(x,y)))\\n\\n\"\n",
    "    \"Return JSON only.\"\n",
    ")\n",
    "\n",
    "user_prompt_template = (\n",
    "    \"Convert the following {num_premises} premises into canonical first-order logic.\\n\\n\"\n",
    "    \"Premises:\\n\"\n",
    "    \"{premises}\\n\\n\"\n",
    "    \"Return a JSON list of exactly {num_premises} strings containing the formulas, in the exact same order.\"\n",
    ")\n",
    "\n",
    "# --- Split FOL dataset before augmentation to prevent data leakage ---\n",
    "has_presplit = all(\"split\" in sample for sample in raw_samples)\n",
    "if has_presplit:\n",
    "    train_fol = [s for s in raw_samples if s.get(\"split\") == \"train\"]\n",
    "    val_fol = [s for s in raw_samples if s.get(\"split\") == \"val\"]\n",
    "    # Track statistics for print compatibility below\n",
    "    train_orig_fol = [s for s in train_fol if \"augmented\" not in str(s.get(\"dataset_source\", \"\"))]\n",
    "    val_orig_fol = val_fol\n",
    "    train_augmented_fol = [s for s in train_fol if \"augmented\" in str(s.get(\"dataset_source\", \"\"))]\n",
    "else:\n",
    "    original_fol = []\n",
    "    augmented_fol = []\n",
    "    for sample in raw_samples:\n",
    "        ds = str(sample.get(\"dataset_source\", \"\"))\n",
    "        if \"augmented\" in ds:\n",
    "            augmented_fol.append(sample)\n",
    "        else:\n",
    "            original_fol.append(sample)\n",
    "\n",
    "    # Shuffle original FOL samples deterministically\n",
    "    random.Random(42).shuffle(original_fol)\n",
    "    split_idx_fol = int(len(original_fol) * 0.9)\n",
    "    train_orig_fol = original_fol[:split_idx_fol]\n",
    "    val_orig_fol = original_fol[split_idx_fol:]\n",
    "\n",
    "    # Map augmented samples back to train split\n",
    "    train_orig_ids = set(x[\"example_id\"] for x in train_orig_fol)\n",
    "\n",
    "    def get_original_id(example_id):\n",
    "        for suffix in [\"_aug_var\", \"_perm_var\", \"_neg_var\"]:\n",
    "            if suffix in example_id:\n",
    "                return example_id.split(suffix)[0]\n",
    "        return example_id\n",
    "\n",
    "    train_augmented_fol = []\n",
    "    for sample in augmented_fol:\n",
    "        base_id = get_original_id(sample[\"example_id\"])\n",
    "        if base_id in train_orig_ids:\n",
    "            train_augmented_fol.append(sample)\n",
    "\n",
    "    # Combine splits\n",
    "    train_fol = train_orig_fol + train_augmented_fol\n",
    "    val_fol = val_orig_fol\n",
    "\n",
    "# --- Split Physics dataset deterministically ---\n",
    "random.Random(42).shuffle(physics_samples)\n",
    "split_idx_phys = int(len(physics_samples) * 0.9)\n",
    "train_physics = physics_samples[:split_idx_phys]\n",
    "val_physics = physics_samples[split_idx_phys:]\n",
    "\n",
    "# --- Format training and validation samples ---\n",
    "def format_samples(fol_list, physics_list):\n",
    "    formatted = []\n",
    "    \n",
    "    # Format FOL translation samples\n",
    "    for item in fol_list:\n",
    "        nl_list = item[\"premises-NL\"]\n",
    "        fol_list_item = item[\"premises-FOL\"]\n",
    "        \n",
    "        nl_content = \"\"\n",
    "        for i, nl in enumerate(nl_list, start=1):\n",
    "            nl_content += f\"{i}. {nl}\\n\"\n",
    "            \n",
    "        user_prompt = user_prompt_template.format(num_premises=len(nl_list), premises=nl_content.strip())\n",
    "        assistant_response = json.dumps(fol_list_item, indent=2)\n",
    "        \n",
    "        formatted.append({\n",
    "            \"messages\": [\n",
    "                {\"role\": \"system\", \"content\": system_prompt_template},\n",
    "                {\"role\": \"user\", \"content\": user_prompt.strip()},\n",
    "                {\"role\": \"assistant\", \"content\": assistant_response.strip()}\n",
    "            ]\n",
    "        })\n",
    "        \n",
    "    # Format Physics samples\n",
    "    for item in physics_list:\n",
    "        physics_input = item[\"input\"]\n",
    "        physics_output = item[\"output\"]\n",
    "        \n",
    "        formatted.append({\n",
    "            \"messages\": [\n",
    "                {\"role\": \"system\", \"content\": physics_system_prompt},\n",
    "                {\"role\": \"user\", \"content\": physics_input.strip()},\n",
    "                {\"role\": \"assistant\", \"content\": physics_output.strip()}\n",
    "            ]\n",
    "        })\n",
    "        \n",
    "    return formatted\n",
    "\n",
    "formatted_train = format_samples(train_fol, train_physics)\n",
    "formatted_val = format_samples(val_fol, val_physics)\n",
    "\n",
    "train_dataset = Dataset.from_list(formatted_train)\n",
    "val_dataset = Dataset.from_list(formatted_val)\n",
    "\n",
    "def apply_template(batch):\n",
    "    texts = []\n",
    "    for messages in batch[\"messages\"]:\n",
    "        text = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=False)\n",
    "        texts.append(text)\n",
    "    return {\"text\": texts}\n",
    "\n",
    "train_dataset = train_dataset.map(apply_template, batched=True, remove_columns=[\"messages\"])\n",
    "val_dataset = val_dataset.map(apply_template, batched=True, remove_columns=[\"messages\"])\n",
    "\n",
    "# Shuffle the final HF datasets\n",
    "train_dataset = train_dataset.shuffle(seed=42)\n",
    "val_dataset = val_dataset.shuffle(seed=42)\n",
    "\n",
    "print(f\"FOL Train/Val Split: original train={len(train_orig_fol)}, original val={len(val_orig_fol)}\")\n",
    "print(f\"FOL Augmented added to Train: {len(train_augmented_fol)}\")\n",
    "print(f\"Physics Train/Val Split: train={len(train_physics)}, val={len(val_physics)}\")\n",
    "print(f\"Total Train size: {len(train_dataset)}, Total Val size: {len(val_dataset)}\")\n"
]

format_cell["source"] = new_format_source

with open(ipynb_path, "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)

print("Successfully patched train_folc_kaggle.ipynb!")
