import json

notebook_path = r"d:\mduy\source\repos\EXACT\src\llm\tuning\train_folc_kaggle.ipynb"

# 1. Define new lines for Cell 5 (removing task_id)
cell5_lines = [
    "# 5. Format Dataset (Chat Template) and split Train/Val\n",
    "import os\n",
    "import json\n",
    "import random\n",
    "from datasets import Dataset\n",
    "\n",
    "# Define prompt templates for flat JSON list output with strict count constraint\n",
    "system_prompt_template = (\n",
    '    "You convert natural-language premises into parser-safe first-order logic formulas.\\n\\n"\n',
    '    "Output a STRICT valid JSON list of strings containing the first-order logic formulas in the exact order of the input premises.\\n"\n',
    '    "You must output EXACTLY the same number of formulas as the input premises. Do not skip any premises or merge them.\\n\\n"\n',
    '    "ALLOWED OPERATORS:\\n"\n',
    '    "AND, OR, NOT, ->, <->, =, !=, >=, <=, >, <, ForAll, Exists\\n\\n"\n',
    '    "QUANTIFIER RULES:\\n"\n',
    '    "Use nested quantifiers only. E.g., ForAll(x, ForAll(y, P(x,y)))\\n\\n"\n',
    '    "Return JSON only."\n',
    ")\n",
    "\n",
    "user_prompt_template = (\n",
    '    "Convert the following {num_premises} premises into canonical first-order logic.\\n\\n"\n',
    '    "Premises:\\n"\n',
    '    "{premises}\\n\\n"\n',
    '    "Return a JSON list of exactly {num_premises} strings containing the formulas, in the exact same order."\n',
    ")\n",
    "\n",
    "# --- Split FOL dataset before augmentation to prevent data leakage ---\n",
    "original_fol = []\n",
    "augmented_fol = []\n",
    "for sample in raw_samples:\n",
    '    ds = str(sample.get("dataset_source", ""))\n',
    '    if "augmented" in ds:\n',
    "        augmented_fol.append(sample)\n",
    "    else:\n",
    "        original_fol.append(sample)\n",
    "\n",
    "# Shuffle original FOL samples deterministically\n",
    "random.Random(42).shuffle(original_fol)\n",
    "split_idx_fol = int(len(original_fol) * 0.9)\n",
    "train_orig_fol = original_fol[:split_idx_fol]\n",
    "val_orig_fol = original_fol[split_idx_fol:]\n",
    "\n",
    "# Map augmented samples back to train split\n",
    'train_orig_ids = set(x["example_id"] for x in train_orig_fol)\n',
    "\n",
    "def get_original_id(example_id):\n",
    '    for suffix in ["_aug_var", "_perm_var", "_neg_var"]:\n',
    "        if suffix in example_id:\n",
    '            return example_id.split(suffix)[0]\n',
    "    return example_id\n",
    "\n",
    "train_augmented_fol = []\n",
    "for sample in augmented_fol:\n",
    '    base_id = get_original_id(sample["example_id"])\n',
    "    if base_id in train_orig_ids:\n",
    "        train_augmented_fol.append(sample)\n",
    "\n",
    "# Combine splits\n",
    "train_fol = train_orig_fol + train_augmented_fol\n",
    "val_fol = val_orig_fol\n",
    "\n",
    "# --- Split Physics dataset deterministically ---\n",
    "random.Random(42).shuffle(physics_samples)\n",
    "split_idx_phys = int(len(physics_samples) * 0.9)\n",
    "train_physics = physics_samples[:split_idx_phys]\n",
    "val_physics = physics_samples[split_idx_phys:]\n",
    "\n",
    "# --- Format training and validation samples ---\n",
    "def format_samples(fol_list, physics_list):\n",
    "    formatted = []\n",
    "    \n",
    "    # Format FOL translation samples\n",
    "    for item in fol_list:\n",
    '        nl_list = item["premises-NL"]\n',
    '        fol_list_item = item["premises-FOL"]\n',
    "        \n",
    '        nl_content = ""\n',
    "        for i, nl in enumerate(nl_list, start=1):\n",
    '            nl_content += f"{i}. {nl}\\n"\n',
    "            \n",
    '        user_prompt = user_prompt_template.format(num_premises=len(nl_list), premises=nl_content.strip())\n',
    "        assistant_response = json.dumps(fol_list_item, indent=2)\n",
    "        \n",
    "        formatted.append({\n",
    '            "messages": [\n',
    '                {"role": "system", "content": system_prompt_template},\n',
    '                {"role": "user", "content": user_prompt.strip()},\n',
    '                {"role": "assistant", "content": assistant_response.strip()}\n',
    "            ]\n",
    "        })\n",
    "        \n",
    "    # Format Physics samples\n",
    "    for item in physics_list:\n",
    '        physics_input = item["input"]\n',
    '        physics_output = item["output"]\n',
    "        \n",
    "        formatted.append({\n",
    '            "messages": [\n',
    '                {"role": "system", "content": physics_system_prompt},\n',
    '                {"role": "user", "content": physics_input.strip()},\n',
    '                {"role": "assistant", "content": physics_output.strip()}\n',
    "            ]\n",
    "        })\n",
    "        \n",
    "    return formatted\n",
    "\n",
    "formatted_train = format_samples(train_fol, train_physics)\n",
    "formatted_val = format_samples(val_fol, val_physics)\n",
    "\n",
    "train_dataset = Dataset.from_list(formatted_train)\n",
    "val_dataset = Dataset.from_list(formatted_val)\n",
    "\n",
    "def apply_template(batch):\n",
    "    texts = []\n",
    '    for messages in batch["messages"]:\n',
    "        text = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=False)\n",
    "        texts.append(text)\n",
    '    return {"text": texts}\n',
    "\n",
    'train_dataset = train_dataset.map(apply_template, batched=True, remove_columns=["messages"])\n',
    'val_dataset = val_dataset.map(apply_template, batched=True, remove_columns=["messages"])\n',
    "\n",
    "# Shuffle the final HF datasets\n",
    "train_dataset = train_dataset.shuffle(seed=42)\n",
    "val_dataset = val_dataset.shuffle(seed=42)\n",
    "\n",
    'print(f"FOL Train/Val Split: original train={len(train_orig_fol)}, original val={len(val_orig_fol)}")\n',
    'print(f"FOL Augmented added to Train: {len(train_augmented_fol)}")\n',
    'print(f"Physics Train/Val Split: train={len(train_physics)}, val={len(val_physics)}")\n',
    'print(f"Total Train size: {len(train_dataset)}, Total Val size: {len(val_dataset)}")\n'
]

# 2. Define new lines for Cell 6 (removing CustomSFTTrainer, using standard SFTTrainer)
cell6_lines = [
    "# 6. Configure SFTTrainer and start training\n",
    "import os\n",
    "import glob\n",
    "import torch\n",
    "from trl import SFTTrainer, SFTConfig\n",
    "from transformers import TrainerCallback, DataCollatorForLanguageModeling\n",
    "from typing import Dict, Union, Any, Optional, List, Tuple\n",
    "\n",
    "class LossLoggingCallback(TrainerCallback):\n",
    "    def on_log(self, args, state, control, logs=None, **kwargs):\n",
    "        if logs is not None:\n",
    '            if "loss" in logs:\n',
    '                print(f"Step {state.global_step}: training_loss = {logs[\'loss\']:.6f}")\n',
    '            if "eval_loss" in logs:\n',
    '                print(f"Step {state.global_step}: validation_loss = {logs[\'eval_loss\']:.6f}")\n',
    "\n",
    "class CustomDataCollator(DataCollatorForLanguageModeling):\n",
    "    def __init__(self, response_template, tokenizer, *args, **kwargs):\n",
    "        super().__init__(tokenizer=tokenizer, mlm=False, *args, **kwargs)\n",
    "        self.response_template = response_template\n",
    "        self.response_token_ids = self.tokenizer.encode(self.response_template, add_special_tokens=False)\n",
    "        \n",
    "    def __call__(self, examples):\n",
    "        batch = super().__call__(examples)\n",
    '        labels = batch["labels"]\n',
    "        for i in range(labels.size(0)):\n",
    '            input_ids = batch["input_ids"][i].tolist()\n',
    "            response_idx = -1\n",
    "            n_template = len(self.response_token_ids)\n",
    "            for j in range(len(input_ids) - n_template + 1):\n",
    "                if input_ids[j:j+n_template] == self.response_token_ids:\n",
    "                    response_idx = j + n_template\n",
    "                    break\n",
    "            \n",
    "            if response_idx != -1:\n",
    "                labels[i, :response_idx] = -100\n",
    "                \n",
    "        return batch\n",
    "\n",
    "# Mathematically exact, dynamic warmup steps calculation based on actual dataset size\n",
    "num_samples = len(train_dataset)\n",
    "effective_batch_size = BATCH_SIZE * GRADIENT_ACCUMULATION\n",
    "steps_per_epoch = num_samples // effective_batch_size\n",
    "if num_samples % effective_batch_size != 0:\n",
    "    steps_per_epoch += 1\n",
    "total_steps = steps_per_epoch * EPOCHS\n",
    "\n",
    "# Target exactly 5% warmup steps of total training steps (HF v5.2 compliant integer steps)\n",
    "warmup_steps = max(1, int(total_steps * 0.05))\n",
    'print(f"Training on {num_samples} samples. Steps per epoch: {steps_per_epoch}. Total steps: {total_steps}. Dynamic warmup steps: {warmup_steps}")\n',
    "\n",
    "# Highly Optimized SFTConfig with Cosine Decay Scheduler & Warmup\n",
    "sft_config = SFTConfig(\n",
    "    output_dir=OUTPUT_DIR,\n",
    "    num_train_epochs=EPOCHS,\n",
    "    per_device_train_batch_size=BATCH_SIZE,\n",
    "    gradient_accumulation_steps=GRADIENT_ACCUMULATION,\n",
    '    eval_strategy="epoch",\n',
    '    save_strategy="epoch",\n',
    "    learning_rate=LEARNING_RATE,\n",
    '    lr_scheduler_type="cosine",             # Cosine learning rate decay scheduler\n',
    "    warmup_steps=warmup_steps,              # Compliant, dynamic warm-up steps to stabilize updates\n",
    "    fp16=use_fp16,\n",
    "    bf16=use_bf16,\n",
    "    logging_steps=1,\n",
    "    logging_first_step=True,\n",
    '    optim="adamw_torch",\n',
    "    gradient_checkpointing=GRADIENT_CHECKPOINTING,\n",
    '    gradient_checkpointing_kwargs={"use_reentrant": False},\n',
    "    per_device_eval_batch_size=BATCH_SIZE,\n",
    '    report_to="none",\n',
    "    load_best_model_at_end=True,\n",
    '    metric_for_best_model="eval_loss",\n',
    "    greater_is_better=False,\n",
    "    save_total_limit=2,\n",
    '    dataset_text_field="text",\n',
    "    max_length=MAX_LENGTH,\n",
    "    neftune_noise_alpha=None,\n",
    "    dataloader_num_workers=2,\n",
    "    dataloader_pin_memory=True\n",
    ")\n",
    "\n",
    'response_template = "<|im_start|>assistant\\n"\n',
    "collator = CustomDataCollator(\n",
    "    response_template=response_template, \n",
    "    tokenizer=tokenizer\n",
    ")\n",
    "\n",
    "trainer = SFTTrainer(\n",
    "    model=model,\n",
    "    train_dataset=train_dataset,\n",
    "    eval_dataset=val_dataset,\n",
    "    processing_class=tokenizer,\n",
    "    args=sft_config,\n",
    "    data_collator=collator,\n",
    "    callbacks=[LossLoggingCallback()]\n",
    ")\n",
    "\n",
    'checkpoints = glob.glob(os.path.join(OUTPUT_DIR, "checkpoint-*"))\n',
    "resume_path = None\n",
    "if checkpoints:\n",
    '    checkpoints.sort(key=lambda x: int(x.split("-")[-1]))\n',
    "    resume_path = checkpoints[-1]\n",
    '    print(f"Found checkpoints. Resuming training from: {resume_path}")\n',
    "\n",
    "trainer.train(resume_from_checkpoint=resume_path)\n",
    "\n",
    'print(f"Saving best validation adapter weights and tokenizer to {OUTPUT_DIR}...")\n',
    "trainer.save_model(OUTPUT_DIR)\n",
    "tokenizer.save_pretrained(OUTPUT_DIR)\n",
    'print("Training completed successfully!")\n'
]

# 3. Read notebook
with open(notebook_path, "r", encoding="utf-8") as f:
    nb = json.load(f)

# 4. Find the cells by ID and replace their source
found_5 = False
found_6 = False
for cell in nb["cells"]:
    if cell.get("id") == "2712f8d5":
        cell["source"] = cell5_lines
        found_5 = True
    elif cell.get("id") == "0ece368f":
        cell["source"] = cell6_lines
        found_6 = True

if found_5 and found_6:
    with open(notebook_path, "w", encoding="utf-8") as f:
        json.dump(nb, f, indent=1, ensure_ascii=False)
    print("Notebook cells updated successfully.")
else:
    print(f"Cells check - Cell 5: {found_5}, Cell 6: {found_6}")
