import json

notebook_path = r"d:\mduy\source\repos\EXACT\src\llm\tuning\train_folc_kaggle.ipynb"

# 1. Define new lines for Cell 4 (helper functions and tokenizer loading)
cell4_lines = [
    "# 4. Initialize Tokenizer and Load Helper Functions\n",
    "import os\n",
    "import sys\n",
    "import gc\n",
    "import torch\n",
    "from transformers import AutoModelForCausalLM, AutoTokenizer\n",
    "from peft import LoraConfig, get_peft_model, PeftModel\n",
    "\n",
    "device = \"cuda\" if torch.cuda.is_available() else \"cpu\"\n",
    "print(f\"Using device: {device}\")\n",
    "if torch.cuda.is_available():\n",
    '    print(f"GPU: {torch.cuda.get_device_name(0)}")\n',
    "\n",
    "# Check hardware bfloat16 support\n",
    "if torch.cuda.is_available() and torch.cuda.is_bf16_supported():\n",
    "    compute_dtype = torch.bfloat16\n",
    "    use_bf16 = True\n",
    "    use_fp16 = False\n",
    '    print("GPU supports bfloat16. Using bfloat16 compute (Optimal for Ampere/Ada/Hopper GPUs like RTX Pro 6000).")\n',
    "else:\n",
    "    compute_dtype = torch.float16\n",
    "    use_bf16 = False\n",
    "    use_fp16 = True\n",
    '    print("Using float16 compute (Standard for Turing/Pascal/Volta GPUs or CPU).")\n',
    "\n",
    "# Select the most optimal Attention implementation\n",
    'attn_impl = "sdpa"\n',
    "try:\n",
    "    import flash_attn\n",
    '    attn_impl = "flash_attention_2"\n',
    '    print("FlashAttention-2 is installed. Using flash_attention_2.")\n',
    "except ImportError:\n",
    '    print("FlashAttention-2 not found. Using PyTorch Native SDPA (Scaled Dot Product Attention).")\n',
    "\n",
    "# Load tokenizer\n",
    "tokenizer = AutoTokenizer.from_pretrained(\n",
    "    MODEL_ID, \n",
    "    trust_remote_code=True, \n",
    "    local_files_only=True\n",
    ")\n",
    "if tokenizer.pad_token is None:\n",
    "    tokenizer.pad_token = tokenizer.eos_token\n",
    "\n",
    "def load_base_model():\n",
    '    print("Loading a fresh instance of the base model...")\n',
    "    model = AutoModelForCausalLM.from_pretrained(\n",
    "        MODEL_ID,\n",
    "        dtype=compute_dtype if torch.cuda.is_available() else torch.float32,\n",
    '        device_map="auto" if torch.cuda.is_available() else None,\n',
    "        trust_remote_code=True,\n",
    "        attn_implementation=attn_impl,\n",
    "        local_files_only=True\n",
    "    )\n",
    "    model.config.use_cache = False\n",
    "    return model\n",
    "\n",
    "def clean_memory():\n",
    "    gc.collect()\n",
    "    if torch.cuda.is_available():\n",
    "        torch.cuda.empty_cache()\n",
    '    print("GPU and system memory cleaned.")\n',
    "\n",
    'target_modules = ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"]\n',
    "\n",
    "# Optimized LoRA Configuration (Rank = 32, Alpha = 64) for logical capacity\n",
    "peft_config = LoraConfig(\n",
    "    r=32,\n",
    "    lora_alpha=64,\n",
    "    target_modules=target_modules,\n",
    "    lora_dropout=0.1,\n",
    '    bias="none",\n',
    '    task_type="CAUSAL_LM"\n',
    ")\n"
]

# 2. Define new lines for Cell 6 (LossLoggingCallback, CustomDataCollator, train_model function, and train call)
cell6_lines = [
    "# 6. Configure SFTTrainer and start training\n",
    "import os\n",
    "import glob\n",
    "import torch\n",
    "from trl import SFTTrainer, SFTConfig\n",
    "from transformers import TrainerCallback, DataCollatorForLanguageModeling\n",
    "from typing import Dict, Union, Any, Optional, List, Tuple\n",
    "\n",
    "class LossLoggingCallback(TrainerCallback):\n",
    "    def on_log(self, args, state, control, logs=None, **kwargs):\n",
    "        if logs is not None:\n",
    '            if "loss" in logs:\n',
    '                print(f"Step {state.global_step}: training_loss = {logs[\'loss\']:.6f}")\n',
    '            if "eval_loss" in logs:\n',
    '                print(f"Step {state.global_step}: validation_loss = {logs[\'eval_loss\']:.6f}")\n',
    "\n",
    "class CustomDataCollator(DataCollatorForLanguageModeling):\n",
    "    def __init__(self, response_template, tokenizer, *args, **kwargs):\n",
    "        super().__init__(tokenizer=tokenizer, mlm=False, *args, **kwargs)\n",
    "        self.response_template = response_template\n",
    "        self.response_token_ids = self.tokenizer.encode(self.response_template, add_special_tokens=False)\n",
    "        \n",
    "    def __call__(self, examples):\n",
    "        batch = super().__call__(examples)\n",
    '        labels = batch["labels"]\n',
    "        for i in range(labels.size(0)):\n",
    '            input_ids = batch["input_ids"][i].tolist()\n',
    "            response_idx = -1\n",
    "            n_template = len(self.response_token_ids)\n",
    "            for j in range(len(input_ids) - n_template + 1):\n",
    "                if input_ids[j:j+n_template] == self.response_token_ids:\n",
    "                    response_idx = j + n_template\n",
    "                    break\n",
    "            \n",
    "            if response_idx != -1:\n",
    "                labels[i, :response_idx] = -100\n",
    "                \n",
    "        return batch\n",
    "\n",
    "def train_model(train_dataset, val_dataset, output_dir):\n",
    "    clean_memory()\n",
    "    \n",
    "    # Mathematically exact, dynamic warmup steps calculation based on actual dataset size\n",
    "    num_samples = len(train_dataset)\n",
    "    effective_batch_size = BATCH_SIZE * GRADIENT_ACCUMULATION\n",
    "    steps_per_epoch = num_samples // effective_batch_size\n",
    "    if num_samples % effective_batch_size != 0:\n",
    "        steps_per_epoch += 1\n",
    "    total_steps = steps_per_epoch * EPOCHS\n",
    "    \n",
    "    # Target exactly 5% warmup steps of total training steps (HF v5.2 compliant integer steps)\n",
    "    warmup_steps = max(1, int(total_steps * 0.05))\n",
    '    print(f"Training on {num_samples} samples. Steps per epoch: {steps_per_epoch}. Total steps: {total_steps}. Dynamic warmup steps: {warmup_steps}")\n',
    "    \n",
    "    base_model = load_base_model()\n",
    "    \n",
    "    # Resume from previous checkpoints if adapter_config.json exists in output_dir\n",
    '    adapter_config_path = os.path.join(output_dir, "adapter_config.json")\n',
    "    if os.path.exists(adapter_config_path):\n",
    '        print(f"Resuming PEFT adapter weights from {output_dir}...")\n',
    "        model = PeftModel.from_pretrained(base_model, output_dir, is_trainable=True)\n",
    "    else:\n",
    '        print("Initializing a new PEFT adapter...")\n',
    "        model = get_peft_model(base_model, peft_config)\n",
    "        \n",
    "    model.print_trainable_parameters()\n",
    "    \n",
    "    # Highly Optimized SFTConfig with Cosine Decay Scheduler & Warmup\n",
    "    sft_config = SFTConfig(\n",
    "        output_dir=output_dir,\n",
    "        num_train_epochs=EPOCHS,\n",
    "        per_device_train_batch_size=BATCH_SIZE,\n",
    "        gradient_accumulation_steps=GRADIENT_ACCUMULATION,\n",
    '        eval_strategy="epoch",\n',
    '        save_strategy="epoch",\n',
    "        learning_rate=LEARNING_RATE,\n",
    '        lr_scheduler_type="cosine",             # Cosine learning rate decay scheduler\n',
    "        warmup_steps=warmup_steps,              # Compliant, dynamic warm-up steps to stabilize updates\n",
    "        fp16=use_fp16,\n",
    "        bf16=use_bf16,\n",
    "        logging_steps=1,\n",
    "        logging_first_step=True,\n",
    '        optim="adamw_torch",\n',
    "        gradient_checkpointing=GRADIENT_CHECKPOINTING,\n",
    '        gradient_checkpointing_kwargs={"use_reentrant": False},\n',
    "        per_device_eval_batch_size=BATCH_SIZE,\n",
    '        report_to="none",\n',
    "        load_best_model_at_end=True,\n",
    '        metric_for_best_model="eval_loss",\n',
    "        greater_is_better=False,\n",
    "        save_total_limit=2,\n",
    '        dataset_text_field="text",\n',
    "        max_length=MAX_LENGTH,\n",
    "        neftune_noise_alpha=None,\n",
    "        dataloader_num_workers=2,\n",
    "        dataloader_pin_memory=True\n",
    ")\n",
    "\n",
    '    response_template = "<|im_start|>assistant\\n"\n',
    "    collator = CustomDataCollator(\n",
    "        response_template=response_template, \n",
    "        tokenizer=tokenizer\n",
    "    )\n",
    "    \n",
    "    trainer = SFTTrainer(\n",
    "        model=model,\n",
    "        train_dataset=train_dataset,\n",
    "        eval_dataset=val_dataset,\n",
    "        processing_class=tokenizer,\n",
    "        args=sft_config,\n",
    "        data_collator=collator,\n",
    "        callbacks=[LossLoggingCallback()]\n",
    "    )\n",
    "    \n",
    '    checkpoints = glob.glob(os.path.join(output_dir, "checkpoint-*"))\n',
    "    resume_path = None\n",
    "    if checkpoints:\n",
    '        checkpoints.sort(key=lambda x: int(x.split("-")[-1]))\n',
    "        resume_path = checkpoints[-1]\n",
    '        print(f"Found checkpoints. Resuming training from: {resume_path}")\n',
    "        \n",
    "    trainer.train(resume_from_checkpoint=resume_path)\n",
    "    \n",
    '    print(f"Saving best validation adapter weights and tokenizer to {output_dir}...")\n',
    "    trainer.save_model(output_dir)\n",
    "    tokenizer.save_pretrained(output_dir)\n",
    '    print("Training completed successfully!")\n',
    "    \n",
    "    # Clean up model & trainer from memory\n",
    "    del trainer\n",
    "    del model\n",
    "    del base_model\n",
    "    clean_memory()\n",
    "\n",
    "# Run training\n",
    "train_model(train_dataset, val_dataset, OUTPUT_DIR)\n"
]

# 3. Read notebook
with open(notebook_path, "r", encoding="utf-8") as f:
    nb = json.load(f)

# 4. Find the cells by ID and replace their source
found_4 = False
found_6 = False
for cell in nb["cells"]:
    if cell.get("id") == "143d68fa":
        cell["source"] = cell4_lines
        found_4 = True
    elif cell.get("id") == "0ece368f":
        cell["source"] = cell6_lines
        found_6 = True

if found_4 and found_6:
    with open(notebook_path, "w", encoding="utf-8") as f:
        json.dump(nb, f, indent=1, ensure_ascii=False)
    print("Notebook cells updated successfully.")
else:
    print(f"Cells check - Cell 4: {found_4}, Cell 6: {found_6}")
