import json

def main():
    notebook_path = r"d:\mduy\source\repos\EXACT\src\llm\tuning\train_folc_kaggle.ipynb"
    
    with open(notebook_path, 'r', encoding='utf-8') as f:
        nb = json.load(f)
        
    print(f"Loaded notebook with {len(nb['cells'])} cells.")
    
    # 1. Update Cell 5 (Dataset split and formatting)
    # We will build a task-balanced dataset by oversampling FOL to match Physics,
    # or by keeping track of task labels to construct batches.
    # Note: To do Task-Balanced Batch sampling with standard SFTTrainer, we can construct the dataset 
    # such that each batch is balanced, or simply oversample the minority class (FOL) to equal the majority (Physics)
    # and shuffle them. Since PyTorch DataLoader is running under SFTTrainer, oversampling FOL beforehand is 
    # the most robust and clean way to get task-balanced batches without custom dataloaders failing under PEFT/SFT.
    
    cell5_source = [
        "# 5. Format Dataset (Chat Template) and split Train/Val\n",
        "import os\n",
        "import json\n",
        "import random\n",
        "from datasets import Dataset\n",
        "\n",
        "# Define prompt templates for flat JSON list output with strict count constraint\n",
        "system_prompt_template = (\n",
        "    \"You convert natural-language premises into parser-safe first-order logic formulas.\\n\\n\"\n",
        "    \"Output a STRICT valid JSON list of strings containing the first-order logic formulas in the exact order of the input premises.\\n\"\n",
        "    \"You must output EXACTLY the same number of formulas as the input premises. Do not skip any premises or merge them.\\n\\n\"\n",
        "    \"ALLOWED OPERATORS:\\n\"\n",
        "    \"AND, OR, NOT, ->, <->, =, !=, >=, <=, >, <, ForAll, Exists\\n\\n\"\n",
        "    \"QUANTIFIER RULES:\\n\"\n",
        "    \"Use nested quantifiers only. E.g., ForAll(x, ForAll(y, P(x,y)))\\n\\n\"\n",
        "    \"Return JSON only.\"\n",
        ")\n",
        "\n",
        "user_prompt_template = (\n",
        "    \"Convert the following {num_premises} premises into canonical first-order logic.\\n\\n\"\n",
        "    \"Premises:\\n\"\n",
        "    \"{premises}\\n\\n\"\n",
        "    \"Return a JSON list of exactly {num_premises} strings containing the formulas, in the exact same order.\"\n",
        ")\n",
        "\n",
        "# --- Split FOL dataset before augmentation to prevent data leakage ---\n",
        "has_presplit = all(\"split\" in sample for sample in raw_samples)\n",
        "if has_presplit:\n",
        "    train_fol = [s for s in raw_samples if s.get(\"split\") == \"train\"]\n",
        "    val_fol = [s for s in raw_samples if s.get(\"split\") == \"val\"]\n",
        "    # Track statistics for print compatibility below\n",
        "    train_orig_fol = [s for s in train_fol if \"augmented\" not in str(s.get(\"dataset_source\", \"\"))]\n",
        "    val_orig_fol = val_fol\n",
        "    train_augmented_fol = [s for s in train_fol if \"augmented\" in str(s.get(\"dataset_source\", \"\))]\n",
        "else:\n",
        "    original_fol = []\n",
        "    augmented_fol = []\n",
        "    for sample in raw_samples:\n",
        "        ds = str(sample.get(\"dataset_source\", \"\"))\n",
        "        if \"augmented\" in ds:\n",
        "            augmented_fol.append(sample)\n",
        "        else:\n",
        "            original_fol.append(sample)\n",
        "\n",
        "    # Shuffle original FOL samples deterministically\n",
        "    random.Random(42).shuffle(original_fol)\n",
        "    split_idx_fol = int(len(original_fol) * 0.9)\n",
        "    train_orig_fol = original_fol[:split_idx_fol]\n",
        "    val_orig_fol = original_fol[split_idx_fol:]\n",
        "\n",
        "    # Map augmented samples back to train split\n",
        "    train_orig_ids = set(x[\"example_id\"] for x in train_orig_fol)\n",
        "\n",
        "    def get_original_id(example_id):\n",
        "        for suffix in [\"_aug_var\", \"_perm_var\", \"_neg_var\"]:\n",
        "            if suffix in example_id:\n",
        "                return example_id.split(suffix)[0]\n",
        "        return example_id\n",
        "\n",
        "    train_augmented_fol = []\n",
        "    for sample in augmented_fol:\n",
        "        base_id = get_original_id(sample[\"example_id\"])\n",
        "        if base_id in train_orig_ids:\n",
        "            train_augmented_fol.append(sample)\n",
        "\n",
        "    # Combine splits\n",
        "    train_fol = train_orig_fol + train_augmented_fol\n",
        "    val_fol = val_orig_fol\n",
        "\n",
        "# --- Split Physics dataset deterministically ---\n",
        "random.Random(42).shuffle(physics_samples)\n",
        "split_idx_phys = int(len(physics_samples) * 0.9)\n",
        "train_physics = physics_samples[:split_idx_phys]\n",
        "val_physics = physics_samples[split_idx_phys:]\n",
        "\n",
        "# --- Format training and validation samples ---\n",
        "def format_samples(fol_list, physics_list, balance_oversample=False):\n",
        "    formatted = []\n",
        "    \n",
        "    fol_samples = []\n",
        "    # Format FOL translation samples\n",
        "    for item in fol_list:\n",
        "        nl_list = item[\"premises-NL\"]\n",
        "        fol_list_item = item[\"premises-FOL\"]\n",
        "        \n",
        "        nl_content = \"\"\n",
        "        for i, nl in enumerate(nl_list, start=1):\n",
        "            nl_content += f\"{i}. {nl}\\n\"\n",
        "            \n",
        "        user_prompt = user_prompt_template.format(num_premises=len(nl_list), premises=nl_content.strip())\n",
        "        assistant_response = json.dumps(fol_list_item, indent=2)\n",
        "        \n",
        "        fol_samples.append({\n",
        "            \"messages\": [\n",
        "                {\"role\": \"system\", \"content\": system_prompt_template},\n",
        "                {\"role\": \"user\", \"content\": user_prompt.strip()},\n",
        "                {\"role\": \"assistant\", \"content\": assistant_response.strip()}\n",
        "            ]\n",
        "        })\n",
        "        \n",
        "    physics_samples_formatted = []\n",
        "    # Format Physics samples\n",
        "    for item in physics_list:\n",
        "        physics_input = item[\"input\"]\n",
        "        physics_output = item[\"output\"]\n",
        "        \n",
        "        physics_samples_formatted.append({\n",
        "            \"messages\": [\n",
        "                {\"role\": \"system\", \"content\": physics_system_prompt},\n",
        "                {\"role\": \"user\", \"content\": physics_input.strip()},\n",
        "                {\"role\": \"assistant\", \"content\": physics_output.strip()}\n",
        "            ]\n",
        "        })\n",
        "        \n",
        "    if balance_oversample:\n",
        "        # Task-Balanced Batch sampling: Oversample FOL samples so that it matches Physics size\n",
        "        # Shuffling them together ensures each batch has a balanced task mixture (close to 50/50)\n",
        "        target_len = max(len(fol_samples), len(physics_samples_formatted))\n",
        "        print(f\"Balancing datasets via oversampling: target size = {target_len}\")\n",
        "        \n",
        "        if len(fol_samples) < target_len:\n",
        "            extra_needed = target_len - len(fol_samples)\n",
        "            fol_samples += random.Random(42).choices(fol_samples, k=extra_needed)\n",
        "        if len(physics_samples_formatted) < target_len:\n",
        "            extra_needed = target_len - len(physics_samples_formatted)\n",
        "            physics_samples_formatted += random.Random(42).choices(physics_samples_formatted, k=extra_needed)\n",
        "            \n",
        "    formatted = fol_samples + physics_samples_formatted\n",
        "    return formatted\n",
        "\n",
        "formatted_train = format_samples(train_fol, train_physics, balance_oversample=True)\n",
        "formatted_val = format_samples(val_fol, val_physics, balance_oversample=False)\n",
        "\n",
        "train_dataset = Dataset.from_list(formatted_train)\n",
        "val_dataset = Dataset.from_list(formatted_val)\n",
        "\n",
        "def apply_template(batch):\n",
        "    texts = []\n",
        "    for messages in batch[\"messages\"]:\n",
        "        text = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=False)\n",
        "        texts.append(text)\n",
        "    return {\"text\": texts}\n",
        "\n",
        "train_dataset = train_dataset.map(apply_template, batched=True, remove_columns=[\"messages\"])\n",
        "val_dataset = val_dataset.map(apply_template, batched=True, remove_columns=[\"messages\"])\n",
        "\n",
        "# Shuffle the final HF datasets\n",
        "train_dataset = train_dataset.shuffle(seed=42)\n",
        "val_dataset = val_dataset.shuffle(seed=42)\n",
        "\n",
        "print(f\"FOL Train/Val Split: original train={len(train_orig_fol)}, original val={len(val_orig_fol)}\")\n",
        "print(f\"FOL Augmented added to Train: {len(train_augmented_fol)}\")\n",
        "print(f\"Physics Train/Val Split: train={len(train_physics)}, val={len(val_physics)}\")\n",
        "print(f\"Total Train size (with oversampling): {len(train_dataset)}, Total Val size: {len(val_dataset)}\")\n"
    ]
    
    # 2. Update Cell 6 (CustomDataCollator and CustomSFTTrainer to implement loss weighting)
    cell6_source = [
        "# 6. Configure Custom Trainer for Loss Weighting and start training\n",
        "import os\n",
        "import glob\n",
        "import torch\n",
        "import torch.nn as nn\n",
        "from trl import SFTTrainer, SFTConfig\n",
        "from transformers import TrainerCallback, DataCollatorForLanguageModeling\n",
        "from typing import Dict, Union, Any, Optional, List, Tuple\n",
        "\n",
        "class LossLoggingCallback(TrainerCallback):\n",
        "    def on_log(self, args, state, control, logs=None, **kwargs):\n",
        "        if logs is not None:\n",
        "            if \"loss\" in logs:\n",
        "                print(f\"Step {state.global_step}: training_loss = {logs['loss']:.6f}\")\n",
        "            if \"eval_loss\" in logs:\n",
        "                print(f\"Step {state.global_step}: validation_loss = {logs['eval_loss']:.6f}\")\n",
        "\n",
        "class CustomDataCollator(DataCollatorForLanguageModeling):\n",
        "    def __init__(self, response_template, tokenizer, *args, **kwargs):\n",
        "        super().__init__(tokenizer=tokenizer, mlm=False, *args, **kwargs)\n",
        "        self.response_template = response_template\n",
        "        self.response_token_ids = self.tokenizer.encode(self.response_template, add_special_tokens=False)\n",
        "        \n",
        "    def __call__(self, examples):\n",
        "        batch = super().__call__(examples)\n",
        "        labels = batch[\"labels\"]\n",
        "        for i in range(labels.size(0)):\n",
        "            input_ids = batch[\"input_ids\"][i].tolist()\n",
        "            response_idx = -1\n",
        "            n_template = len(self.response_token_ids)\n",
        "            for j in range(len(input_ids) - n_template + 1):\n",
        "                if input_ids[j:j+n_template] == self.response_token_ids:\n",
        "                    response_idx = j + n_template\n",
        "                    break\n",
        "            \n",
        "            if response_idx != -1:\n",
        "                labels[i, :response_idx] = -100\n",
        "                \n",
        "        return batch\n",
        "\n",
        "class CustomSFTTrainer(SFTTrainer):\n",
        "    def compute_loss(self, model, inputs, return_outputs=False, **kwargs):\n",
        "        \"\"\"\n",
        "        Custom loss computation to apply task-specific loss weighting.\n",
        "        Task classification: FOL (system prompt prefix [2610, 5508]) vs Physics (prefix [2610, 525]).\n",
        "        \"\"\"\n",
        "        if \"labels\" not in inputs:\n",
        "            return super().compute_loss(model, inputs, return_outputs, **kwargs)\n",
        "            \n",
        "        # Extract labels and inputs\n",
        "        labels = inputs[\"labels\"]\n",
        "        input_ids = inputs[\"input_ids\"]\n",
        "        \n",
        "        # We call the model to get logits\n",
        "        outputs = model(**inputs)\n",
        "        logits = outputs.get(\"logits\")\n",
        "        \n",
        "        # Shift logits and labels for causal LM loss calculation\n",
        "        shift_logits = logits[..., :-1, :].contiguous()\n",
        "        shift_labels = labels[..., 1:].contiguous()\n",
        "        \n",
        "        # Set up loss function with reduction='none' so we can weight per sequence\n",
        "        loss_fct = nn.CrossEntropyLoss(reduction=\"none\")\n",
        "        \n",
        "        # Flatten logits and labels\n",
        "        vocab_size = shift_logits.size(-1)\n",
        "        flat_logits = shift_logits.view(-1, vocab_size)\n",
        "        flat_labels = shift_labels.view(-1)\n",
        "        \n",
        "        # Compute token-level losses\n",
        "        token_losses = loss_fct(flat_logits, flat_labels)\n",
        "        token_losses = token_losses.view(shift_labels.size())\n",
        "        \n",
        "        # Apply sequence-level loss weighting based on task type\n",
        "        # We detect the task by checking the system prompt token sequence in input_ids\n",
        "        weighted_losses = []\n",
        "        for i in range(input_ids.size(0)):\n",
        "            seq_input_ids = input_ids[i].tolist()\n",
        "            seq_losses = token_losses[i]\n",
        "            seq_labels = shift_labels[i]\n",
        "            \n",
        "            # Detect if it's FOL task\n",
        "            # Prefix check: FOL starts system prompt with 'You convert' (tokens [2610, 5508])\n",
        "            is_fol = False\n",
        "            for idx in range(len(seq_input_ids) - 5):\n",
        "                # Search within first 20 tokens to find system prompt prefix\n",
        "                if idx > 20:\n",
        "                    break\n",
        "                if seq_input_ids[idx] == 2610 and seq_input_ids[idx+1] == 5508:\n",
        "                    is_fol = True\n",
        "                    break\n",
        "            \n",
        "            # Mask out non-active label tokens (-100)\n",
        "            valid_mask = (seq_labels != -100)\n",
        "            active_losses = seq_losses[valid_mask]\n",
        "            \n",
        "            if len(active_losses) > 0:\n",
        "                mean_loss = active_losses.mean()\n",
        "                # Physics response has ~10x more tokens than FOL. We weight FOL loss higher to compensate.\n",
        "                # FOL loss weight = 3.0, Physics loss weight = 1.0\n",
        "                weight = 3.0 if is_fol else 1.0\n",
        "                weighted_losses.append(mean_loss * weight)\n",
        "            else:\n",
        "                weighted_losses.append(torch.tensor(0.0, device=logits.device, dtype=logits.dtype))\n",
        "                \n",
        "        loss = torch.stack(weighted_losses).mean()\n",
        "        \n",
        "        return (loss, outputs) if return_outputs else loss\n",
        "\n",
        "def train_model(train_dataset, val_dataset, output_dir):\n",
        "    clean_memory()\n",
        "    \n",
        "    # Mathematically exact, dynamic warmup steps calculation based on actual dataset size\n",
        "    num_samples = len(train_dataset)\n",
        "    effective_batch_size = BATCH_SIZE * GRADIENT_ACCUMULATION\n",
        "    steps_per_epoch = num_samples // effective_batch_size\n",
        "    if num_samples % effective_batch_size != 0:\n",
        "        steps_per_epoch += 1\n",
        "    total_steps = steps_per_epoch * EPOCHS\n",
        "    \n",
        "    # Target exactly 5% warmup steps of total training steps (HF v5.2 compliant integer steps)\n",
        "    warmup_steps = max(1, int(total_steps * 0.05))\n",
        "    print(f\"Training on {num_samples} samples. Steps per epoch: {steps_per_epoch}. Total steps: {total_steps}. Dynamic warmup steps: {warmup_steps}\")\n",
        "    \n",
        "    base_model = load_base_model()\n",
        "    \n",
        "    # Resume from previous checkpoints if adapter_config.json exists in output_dir\n",
        "    adapter_config_path = os.path.join(output_dir, \"adapter_config.json\")\n",
        "    if os.path.exists(adapter_config_path):\n",
        "        print(f\"Resuming PEFT adapter weights from {output_dir}...\")\n",
        "        model = PeftModel.from_pretrained(base_model, output_dir, is_trainable=True)\n",
        "    else:\n",
        "        print(\"Initializing a new PEFT adapter...\")\n",
        "        model = get_peft_model(base_model, peft_config)\n",
        "        \n",
        "    model.print_trainable_parameters()\n",
        "    \n",
        "    # Highly Optimized SFTConfig with Cosine Decay Scheduler & Warmup\n",
        "    sft_config = SFTConfig(\n",
        "        output_dir=output_dir,\n",
        "        num_train_epochs=EPOCHS,\n",
        "        per_device_train_batch_size=BATCH_SIZE,\n",
        "        gradient_accumulation_steps=GRADIENT_ACCUMULATION,\n",
        "        eval_strategy=\"epoch\",\n",
        "        save_strategy=\"epoch\",\n",
        "        learning_rate=LEARNING_RATE,\n",
        "        lr_scheduler_type=\"cosine\",             # Cosine learning rate decay scheduler\n",
        "        warmup_steps=warmup_steps,              # Compliant, dynamic warm-up steps to stabilize updates\n",
        "        fp16=use_fp16,\n",
        "        bf16=use_bf16,\n",
        "        logging_steps=1,\n",
        "        logging_first_step=True,\n",
        "        optim=\"adamw_torch_fused\",\n",
        "        gradient_checkpointing=GRADIENT_CHECKPOINTING,\n",
        "        gradient_checkpointing_kwargs={\"use_reentrant\": False},\n",
        "        per_device_eval_batch_size=BATCH_SIZE,\n",
        "        report_to=\"none\",\n",
        "        load_best_model_at_end=True,\n",
        "        metric_for_best_model=\"eval_loss\",\n",
        "        greater_is_better=False,\n",
        "        save_total_limit=2,\n",
        "        dataset_text_field=\"text\",\n",
        "        max_length=MAX_LENGTH,\n",
        "        neftune_noise_alpha=None,\n",
        "        dataloader_num_workers=2,\n",
        "        dataloader_pin_memory=True\n",
        "    )\n",
        "\n",
        "    response_template = \"<|im_start|>assistant\\n\"\n",
        "    collator = CustomDataCollator(\n",
        "        response_template=response_template, \n",
        "        tokenizer=tokenizer\n",
        "    )\n",
        "    \n",
        "    trainer = CustomSFTTrainer(\n",
        "        model=model,\n",
        "        train_dataset=train_dataset,\n",
        "        eval_dataset=val_dataset,\n",
        "        processing_class=tokenizer,\n",
        "        args=sft_config,\n",
        "        data_collator=collator,\n",
        "        callbacks=[LossLoggingCallback()]\n",
        "    )\n",
        "\n",
        "    checkpoints = glob.glob(os.path.join(output_dir, \"checkpoint-*\"))\n",
        "    resume_path = None\n",
        "    if checkpoints:\n",
        "        checkpoints.sort(key=lambda x: int(x.split(\"-\")[-1]))\n",
        "        resume_path = checkpoints[-1]\n",
        "        print(f\"Found checkpoints. Resuming training from: {resume_path}\")\n",
        "        \n",
        "    trainer.train(resume_from_checkpoint=resume_path)\n",
        "    \n",
        "    print(f\"Saving best validation adapter weights and tokenizer to {output_dir}...\")\n",
        "    trainer.save_model(output_dir)\n",
        "    tokenizer.save_pretrained(output_dir)\n",
        "    print(\"Training completed successfully!\")\n",
        "    \n",
        "    # --- POST-TRAINING ACCURACY EVALUATION ---\n",
        "    try:\n",
        "        print(\"\\n=== Starting Post-Training Accuracy Evaluation ===\")\n",
        "        model.eval()\n",
        "        evaluate_fol_accuracy(model, tokenizer, val_fol, limit=None)\n",
        "        evaluate_physics_accuracy(model, tokenizer, val_physics, limit=None)\n",
        "    except Exception as e:\n",
        "        print(f\"Error during post-training evaluation: {e}\")\n",
        "    \n",
        "    # Clean up model & trainer from memory\n",
        "    del trainer\n",
        "    del model\n",
        "    del base_model\n",
        "    clean_memory()\n"
    ]
    
    # 3. Replace cells in the notebook structure
    found_5 = False
    found_6 = False
    
    for cell in nb['cells']:
        if cell.get('cell_type') == 'code':
            if cell.get('id') == '2712f8d5':
                cell['source'] = cell5_source
                found_5 = True
                print("Patched Cell 5 (dataset split & balanced oversampling)")
            elif cell.get('id') == '0ece368f':
                cell['source'] = cell6_source
                found_6 = True
                print("Patched Cell 6 (CustomSFTTrainer with loss weighting)")
                
    if found_5 and found_6:
        with open(notebook_path, 'w', encoding='utf-8') as f:
            json.dump(nb, f, indent=1, ensure_ascii=False)
        print("Successfully saved patched notebook!")
    else:
        print(f"Error: Could not find cell with ID '2712f8d5' (found: {found_5}) or '0ece368f' (found: {found_6})")

if __name__ == '__main__':
    main()
